<div class="content-wrapper">
  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('order') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Order</li>
    </ol>
    <br>
  </section>


<section class="content">
    <div class="row">
      <div class="col-md-12 col-xs-12">


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        

  <div id="messages"></div>

  <?php if($this->session->flashdata('success')): ?>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <?php echo $this->session->flashdata('success'); ?>
    </div>
  <?php elseif($this->session->flashdata('error')): ?>
    <div class="alert alert-error alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <?php echo $this->session->flashdata('error'); ?>
    </div>
  <?php endif; ?>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                     C R E A T E   O R D E R                                     -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


<form role="form" action="<?php base_url('order/create') ?>" method="post" enctype="multipart/form-data" >

  <?php echo validation_errors(); ?> 

  <div class="box">

    <div class="box-body">

        <div class="row">

          <div class="col-md-10 col-xs-10">
           <h4 class="box-title">Add Order </h4>
          </div>

          <div class="col-md-2 col-xs-2">
            <div class="form-group" style="display: flex">
              <label for="order_no">Order No <?php echo $generate_no['next_no'] ?></label>
                <input type="hidden" class="form-control" id="order_no" name="order_no" autocomplete="off" 
                value="<?php echo $generate_no['next_no'] ?>" readonly />       
               </div>
           </div>
        </div>
     
        <div class="row">          

           <div class="col-md-5 col-xs-5">    
            <div class="form-group">
              <label for="customer">Customer <font color="red"> *</font></label>
              <select class="form-control select_group" id="customer" name="customer">

                <!-- Create can come from the main menu or from the customer edit page.  
                     When it comes from edit customer, we have the customer id and can present the customer in the order -->  

                <?php if(empty($this->session->userdata('customer_id'))): ?>  
                   <option value=""></option> 
                  <?php foreach ($customer as $k => $v): ?>
                  <option value="<?php echo $v['customer_id'] ?>" <?php echo set_select('customer', $v['customer_id']); ?>><?php echo $v['customer_name'] ?> - <?php echo $v['area_name'] ?> - <?php echo $v['municipality_name'] ?></option>
                <?php endforeach ?> 
                  
                <?php else : ?>                 
                   <?php foreach ($customer as $k => $v): ?>
                    <option value="<?php echo $v['customer_id'] ?>" <?php if($this->session->userdata('customer_id') == $v['customer_id']) { echo "selected='selected'"; } ?> ><?php echo $v['customer_name'] ?> - <?php echo $v['area_name'] ?> - <?php echo $v['municipality_name'] ?></option>
                   <?php endforeach ?>
                <?php endif; ?>  

              </select>
            </div>
          </div>

          <div class="col-md-2 col-xs-2">
            <div class="form-group">
              <label for="date">Delivery Date</label>
              <input type="date" class="form-control" id="delivery_date" name="delivery_date" autocomplete="off" 
              value="<?php
                      $date=date_create(date('Y-m-d'));
                      date_add($date,date_interval_create_from_date_string("1 days"));
                      echo date_format($date,"Y-m-d");
                      ?>"/>
            </div>
          </div> 

          <div class="col-md-3 col-xs-3">    
            <div class="form-group">
              <label for="employee">Deliver by</label>
              <select class="form-control select_group" id="employee" name="employee">
                <option value=""></option> 
                <?php foreach ($employee as $k => $v): ?>
                <option value="<?php echo $v['employee_id'] ?>" <?php echo set_select('employee', $v['employee_id']); ?>><?php echo $v['employee_name'] ?></option>
                <?php endforeach ?>
              </select>
            </div>
          </div>

          <div class="col-md-2 col-xs-2">
            <div class="form-group">
              <label for="date">Order Date <font color="red"> *</font></label>
              <input type="date" class="form-control" id="order_date" name="order_date" autocomplete="off" 
              value="<?php echo date('Y-m-d');?>"/>
            </div>
          </div>
        </div>

        <div class="row">

          <div class="col-md-5 col-xs-5"></div>

           <div class="col-md-2 col-xs-2">
            <div class="form-group">
              <label for="order_no">Sales Invoice No</label>
                <input type="text" class="form-control" id="sales_invoice_no" name="sales_invoice_no" autocomplete="off"/>       
               </div>
           </div>

           <div class="col-md-2 col-xs-2">
            <div class="form-group">
              <label for="order_no">Delivery Receipt No</label>
                <input type="text" class="form-control" id="delivery_receipt_no" name="delivery_receipt_no" autocomplete="off"/>       
               </div>
           </div>

            <div class="col-md-2 col-xs-2">
            <div class="form-group">
              <label for="order_no">Purchase Order No</label>
                <input type="text" class="form-control" id="purchase_order_no" name="purchase_order_no" autocomplete="off"/>       
               </div>
           </div>

        </div>      
          
          <br /> 
          <table class="table table-bordered" id="item_info_table">
            <thead>
              <tr>
                <th style="width:50%">Item <font color="red"> *</font></th>
                <th style="width:10%">Qty</th>
                <th style="width:10%">Rate</th>
                <th style="width:20%">Amount</th>
                <th style="width:10%"><button type="button" id="add_row" class="btn btn-default"><i class="fa fa-plus"></i></button></th>
              </tr>
            </thead>

             <tbody>
               <tr id="row_1">
                 <td>
                  <select class="form-control select_group item" data-row-id="row_1" id="item_1" name="item[]" style="width:100%;" onchange="getItemData(1)" required>
                      <option value=""></option>
                      <?php foreach ($item as $k => $v): ?>
                        <option value="<?php echo $v['item_location_id'] ?>">(<?php echo $v['item_code'] ?>) <?php echo $v['item_name'] ?> - <?php echo $v['location_name'] ?></option>
                      <?php endforeach ?>
                    </select>
                  </td>
                  <td><input type="text" name="qty[]" id="qty_1" class="form-control" required onkeyup="getTotal(1)"></td>
                  <td>
                    <input type="text" name="rate[]" id="rate_1" class="form-control" required onkeyup="getTotal(1)">
                  </td>
                  <td>
                    <input type="text" style="text-align:right;" name="amount[]" id="amount_1" class="form-control" disabled autocomplete="off">
                    <input type="hidden" name="amount_value[]" id="amount_value_1" class="form-control" autocomplete="off">
                  </td>
                  <td><button type="button" class="btn btn-default" onclick="removeRow('1')"><i class="fa fa-close"></i></button></td>
               </tr>
             </tbody>
          </table>

          <br /> <br/>

          <div class="col-md-6 col-xs-12 pull pull-right">            
           
            <div class="form-group">
              <label for="order_total" class="col-sm-5 control-label">Total</label>
              <div class="col-sm-5">
                <input type="text" class="form-control" style="text-align:right;" id="order_total" name="order_total" readonly autocomplete="off">
                <input type="hidden" class="form-control" id="order_total_value" name="order_total_value" autocomplete="off">
              </div>
            </div>

          </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Save</button>
          <a href="<?php echo base_url('order/') ?>" class="btn btn-warning">Back</a>
        </div>
      </form>
  </div>
</div>
</div>


</section>
</div>



<!------------------------------------------------------------->
<!-- Javascript part of Order                               --->
<!------------------------------------------------------------->

<script type="text/javascript">
  var base_url = "<?php echo base_url(); ?>";

  $(document).ready(function() {
    $(".select_group").select2();

    
    var btnCust = '<button type="button" class="btn btn-secondary" title="Add picture tags" ' + 
        'onclick="alert(\'Call your custom code here.\')">' +
        '<i class="glyphicon glyphicon-tag"></i>' +
        '</button>'; 
  
    // Add new row in the table 
    $("#add_row").unbind('click').bind('click', function() {
      var table = $("#item_info_table");
      var count_table_tbody_tr = $("#item_info_table tbody tr").length;
      var row_id = count_table_tbody_tr + 1;

      $.ajax({
          url: base_url + '/order/getItemLocationData/',
          type: 'post',
          dataType: 'json',
          success:function(response) {
            
              // console.log(reponse.x);
               var html = '<tr id="row_'+row_id+'">'+
                   '<td>'+ 
                    '<select class="form-control select_group item" data-row-id="'+row_id+'" id="item_'+row_id+'" name="item[]" style="width:100%;" onchange="getItemData('+row_id+')">'+
                        '<option value=""></option>';
                        $.each(response, function(index, value) {
                          html += '<option value="'+value.item_location_id+'">'+'('+value.item_code+') '+value.item_name+' - '+value.location_name+'</option>';                                
                        });
                        
                      html += '</select>'+
                    '</td>'+ 
                    '<td><input type="number" name="qty[]" id="qty_'+row_id+'" class="form-control" onkeyup="getTotal('+row_id+')"></td>'+
                    '<td><input type="text" name="rate[]" id="rate_'+row_id+'" class="form-control" onkeyup="getTotal('+row_id+')"></td>'+
                    '<td><input type="text" name="amount[]" style="text-align:right;" id="amount_'+row_id+'" class="form-control" disabled><input type="hidden" name="amount_value[]" id="amount_value_'+row_id+'" class="form-control"></td>'+
                    '<td><button type="button" class="btn btn-default" onclick="removeRow(\''+row_id+'\')"><i class="fa fa-close"></i></button></td>'+
                    '</tr>';

                if(count_table_tbody_tr >= 1) {
                $("#item_info_table tbody tr:last").after(html);  
              }
              else {
                $("#item_info_table tbody").html(html);
              }

              $(".item").select2();

          }
        });

      return false;
    });

  }); // /document

  function getTotal(row = null) {
    if(row) {
      var total = Number($("#rate_"+row).val()) * Number($("#qty_"+row).val());
      total = total.toFixed(2);
      $("#amount_"+row).val(total);
      $("#amount_value_"+row).val(total);
      
      subAmount();

    } else {
      alert('no row !! please refresh the page');
    }
  }

  // get the item information from the server
  function getItemData(row_id)
  {
    var item_location_id = $("#item_"+row_id).val(); 

    if(item_location_id == "") {
      $("#rate_"+row_id).val("");
      $("#rate_"+row_id).val("");

      $("#qty_"+row_id).val("");           

      $("#amount_"+row_id).val("");
      $("#amount_value_"+row_id).val("");

    } else {
      $.ajax({
        url: base_url + 'order/getItemPrice',
        type: 'post',
        data: {item_location_id : item_location_id},
        dataType: 'json',
        success:function(response) {
          // setting the rate value into the rate input field
          
          $("#rate_"+row_id).val(response.item_price);

          $("#qty_"+row_id).val(1);
          $("#qty_value_"+row_id).val(1);

          var total = Number(response.item_price) * 1;
          total = total.toFixed(2);
          $("#amount_"+row_id).val(total);
          $("#amount_value_"+row_id).val(total);
          
          subAmount();
        } // /success
      }); // /ajax function to fetch the item data 
    }
  }




  // calculate the total amount of the order
  function subAmount() {
   
    var tableItemLength = $("#item_info_table tbody tr").length;
    var totalSubAmount = 0;
    
    for(x = 0; x < tableItemLength; x++) {
      var tr = $("#item_info_table tbody tr")[x];
      var count = $(tr).attr('id');
      count = count.substring(4);

      totalSubAmount = Number(totalSubAmount) + Number($("#amount_"+count).val());
    } // /for

    totalSubAmount = totalSubAmount.toFixed(2);    
    $("#order_total").val(totalSubAmount);
    //$("#order_total_value").val(totalSubAmount);    

  } // /sub total amount

  function removeRow(tr_id)
  {
    $("#item_info_table tbody tr#row_"+tr_id).remove();
    subAmount();
  }
</script>