<div class="content-wrapper">
  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('order') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Order</li>
    </ol>
    <br>
  </section>


  <section class="content">
   <div class="row">
    <div class="col-md-12 col-xs-12"> 


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        

    <div id="messages"></div>

    <?php if($this->session->flashdata('success')): ?>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?php echo $this->session->flashdata('success'); ?>
      </div>
    <?php elseif($this->session->flashdata('error')): ?>
      <div class="alert alert-error alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?php echo $this->session->flashdata('error'); ?>
      </div>
    <?php endif; ?>


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                    E D I T        O R D E R                                     -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


<form role="form" action="<?php base_url('order/update') ?>" method="post">

  <div class="box">
   
        <div class="box-body">

          <?php echo validation_errors(); ?>

          <div class="row">

          <div class="col-md-10 col-xs-10">
           <h4 class="box-title">Update Order </h4>
          </div>

            <div class="col-md-2 col-xs-2">
              <div class="form-group" style="display: flex">
                <label for="order_no">Order No <?php echo $order_data['order']['order_no']; ?></label>              
                <input type="hidden" class="form-control" id="order_no" name="order_no" autocomplete="off" 
                value="<?php echo $order_data['order']['order_no']; ?>" disabled  />
              </div>
            </div>  
        </div>

<!--------------------------------------->
<!-- Box 1                            --->
<!--------------------------------------->        

          <div class="row">           

            <div class="col-md-4 col-xs-4">
                <div class="box box-solid box-default">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="company">Customer <font color="red"> *</font></label>
                        <?php echo '<a href="' . base_url('customer/update/' . $order_data['order']['customer_fk']) . '" class="btn btn-default"><i class="fa fa-search-plus" style="font-size:20px"></i></a>'; ?>       
                      <br>
                      <strong><?php echo $order_data['order']['customer_name']; ?></strong><br>
                      <?php echo 'Phone:  ' . $order_data['order']['phone']; ?><br>
                      <?php echo 'Area:  ' . $order_data['order']['area_name']; ?><br>
                      <?php echo 'Municipality:  ' . $order_data['order']['municipality_name']; ?><br>
                    </div>
                     <input type="hidden" class="form-control" id="customer" name="customer" autocomplete="off" value="<?php echo $order_data['order']['customer_fk']; ?>"/>         
                  </div> 
              </div>         
          </div>  

<!--------------------------------------->
<!-- Box 2                            --->
<!--------------------------------------->            

          <div class="col-md-8 col-xs-8">
            <div class="box box-solid">
              <div class="box-body">
                <div class="row">
                 <div class="col-md-4 col-xs-4">
              <div class="form-group">
                <label for="employee">Deliver by</label>
                <select class="form-control select_group" id="employee" name="employee">
                  <option value=""></option> 
                  <?php foreach ($employee as $k => $v): ?>
                    <option value="<?php echo $v['employee_id'] ?>" <?php if($order_data['order']['employee_fk'] == $v['employee_id']) { echo "selected='selected'"; } ?> ><?php echo $v['employee_name'] ?></option>
                  <?php endforeach ?>
               </select>
              </div>
            </div>

             <div class="col-md-4 col-xs-4">
            <div class="form-group">
              <label for="delivery_date">Delivery Date</label>
              <input type="date" class="form-control" id="delivery_date" name="delivery_date" autocomplete="off" 
              value="<?php echo set_value('delivery_date', isset($order_data['order']['delivery_date']) ? $order_data['order']['delivery_date'] : ''); ?>" align="right"/>
            </div>
          </div> 

            <div class="col-md-4 col-xs-4">
            <div class="form-group">
              <label for="order_date">Order Date <font color="red"> *</font></label>
              <input type="date" class="form-control" id="order_date" name="order_date" autocomplete="off" 
              value="<?php echo set_value('order_date', isset($order_data['order']['order_date']) ? $order_data['order']['order_date'] : ''); ?>" align="right"/>
            </div>
          </div>          
        </div> 

        <div class="row">             

          <div class="col-md-4 col-xs-4">
            <div class="form-group">
              <label for="sales_invoice_no">Sales Invoice No</label>              
              <input type="text" class="form-control" id="sales_invoice_no" name="sales_invoice_no" autocomplete="off" 
              value="<?php echo set_value('sales_invoice_no', isset($order_data['order']['sales_invoice_no']) ? $order_data['order']['sales_invoice_no'] : ''); ?>" align="right"/>
            </div>
          </div> 

          <div class="col-md-4 col-xs-4">
            <div class="form-group">
              <label for="delivery_receipt_no">Delivery Receipt No</label>              
              <input type="text" class="form-control" id="delivery_receipt_no" name="delivery_receipt_no" autocomplete="off" 
              value="<?php echo set_value('delivery_receipt_no', isset($order_data['order']['delivery_receipt_no']) ? $order_data['order']['delivery_receipt_no'] : ''); ?>" align="right"/>
            </div>
          </div> 

          <div class="col-md-4 col-xs-4">
            <div class="form-group">
              <label for="purchase_order_no">Purchase Order No</label>              
              <input type="text" class="form-control" id="purchase_order_no" name="purchase_order_no" autocomplete="off" 
              value="<?php echo set_value('purchase_order_no', isset($order_data['order']['purchase_order_no']) ? $order_data['order']['purchase_order_no'] : ''); ?>" align="right"/>
            </div>
          </div> 
        </div>  

       </div>
      </div>
    </div>
          
<!--------------------------------------->
<!-- Item                             --->
<!--------------------------------------->  

        <table class="table table-bordered" id="item_info_table">
          <thead>
            <tr>
              <th style="width:50%">Item <font color="red"> *</font></th>
              <th style="width:10%">Qty</th>
              <th style="width:10%">Rate</th>
              <th style="width:20%">Amount</th>
              <th style="width:10%"><button type="button" id="add_row" class="btn btn-default"><i class="fa fa-plus"></i></button></th>
            </tr>
          </thead>

           <tbody>

            <?php if(isset($order_data['movement'])): ?>
              <?php $x = 1; ?>
              <?php foreach ($order_data['movement'] as $key => $val): ?>
                <?php //print_r($v); ?>
               <tr id="row_<?php echo $x; ?>">
                 <td>
                  <select class="form-control select_group item" data-row-id="row_<?php echo $x; ?>" id="item_<?php echo $x; ?>" name="item[]" style="width:100%;" onchange="getItemData(<?php echo $x; ?>)" required>
                      <option value=""></option>
                      <?php foreach ($item as $k => $v): ?>
                        <option value="<?php echo $v['item_location_id'] ?>" <?php if($val['item_location_fk'] == $v['item_location_id']) { echo "selected='selected'"; } ?>>(<?php echo $v['item_code'] ?>) <?php echo $v['item_name'] ?> - <?php echo $v['location_name'] ?></option>
                      <?php endforeach ?>
                    </select>
                  </td>
                  <td><input type="text" name="qty[]" id="qty_<?php echo $x; ?>" class="form-control" required onkeyup="getTotal(<?php echo $x; ?>)" value="<?php echo $val['quantity'] ?>" autocomplete="off"></td>
                  <td>
                    <input type="text" name="rate[]" id="rate_<?php echo $x; ?>" class="form-control" required onkeyup="getTotal(<?php echo $x; ?>)"  value="<?php echo $val['rate'] ?>" autocomplete="off">               
                  </td>
            <td>
              <input type="text" name="amount[]" style="text-align:right;" id="amount_<?php echo $x; ?>" class="form-control" disabled value="<?php echo $val['order_amount'] ?>" autocomplete="off">
              <input type="hidden" name="amount_value[]" id="amount_value_<?php echo $x; ?>" class="form-control" value="<?php echo $val['order_amount'] ?>" autocomplete="off">
            </td>
            <td><button type="button" class="btn btn-default" onclick="removeRow('<?php echo $x; ?>')"><i class="fa fa-close"></i></button></td>
         </tr>
         <?php $x++; ?>
       <?php endforeach; ?>
     <?php endif; ?>
     </tbody>
  </table>


    <div class="col-md-6 col-xs-12 pull pull-right">

     <div class="form-group">
        <label for="order_total" class="col-sm-5 control-label">Total</label>
        <div class="col-sm-5" >
          <input type="text" class="form-control" style="text-align:right;" id="order_total" name="order_total" readonly value="<?php echo $order_data['order']['order_total'] ?>" autocomplete="off" >
          <input type="hidden" class="form-control" id="order_total_value" name="order_total_value" value="<?php echo $order_data['order']['order_total'] ?>" autocomplete="off">
        </div>
      </div>

      <div class="form-group">
        <label for="previous_balance" class="col-sm-5 control-label">+ Previous Balance</label>
        <div class="col-sm-5">
          <input type="text" class="form-control" style="text-align:right;" id="previous_balance" name="previous_balance" disabled value="<?php echo $order_data['order']['previous_balance'] ?>" readonly >
          <input type="hidden" class="form-control" id="previous_balance_value" name="previous_balance_value" value="<?php echo $order_data['order']['previous_balance'] ?>" autocomplete="off">
        </div>
      </div> 

      <div class="form-group">
        <label for="amount_due" class="col-sm-5 control-label">Amount Due</label>
        <div class="col-sm-5">
          <input type="text" class="form-control" style="text-align:right;" id="amount_due" name="amount_due" value="<?php echo $order_data['order']['balance'] ?>" readonly >
        </div>
      </div>

    </div>
  </div>



  <div class="box-footer">

    <div class="row">
      <div class="col-md-6 col-xs-6">
        <button type="submit" class="btn btn-primary">Save</button>
        <?php echo '<a href="'.base_url('report_order_slip/report_order_slip/'.$order_data['order']['order_id']).'" target="_blank" class="btn btn-success"><i class="fa fa-print" ></i></a>'; ?>
        <a href="<?php echo base_url('order/create') ?>" class="btn btn-success">Create New Order</a>
        <a href="<?php echo base_url('order/') ?>" class="btn btn-warning">Back</a>
      </div>

      <div class="col-md-6 col-xs-6" align="right" >
        Updated by <?php echo $order_data['order']['updated_by'] ?> on <?php echo $order_data['order']['updated_date'] ?> 
      </div>
    </div>

  </div>



</form>
</div>
</div>
</div>


</section>
</div>



<!------------------------------------------------------------->
<!-- Javascript part of Order                               --->
<!------------------------------------------------------------->

<script type="text/javascript">
  var base_url = "<?php echo base_url(); ?>";

   $(document).ready(function() {
    $(".select_group").select2();

    
    // Add new row in the table 
    $("#add_row").unbind('click').bind('click', function() {
      var table = $("#item_info_table");
      var count_table_tbody_tr = $("#item_info_table tbody tr").length;
      var row_id = count_table_tbody_tr + 1;

      $.ajax({
          url: base_url + '/order/getItemLocationData/',
          type: 'post',
          dataType: 'json',
          success:function(response) {
            

              // console.log(reponse.x);
               var html = '<tr id="row_'+row_id+'">'+
                   '<td>'+ 
                    '<select class="form-control select_group item" data-row-id="'+row_id+'" id="item_'+row_id+'" name="item[]" style="width:100%;" onchange="getItemData('+row_id+')">'+
                        '<option value=""></option>';
                        $.each(response, function(index, value) {
                          html += '<option value="'+value.item_location_id+'">('+value.item_code+') '+value.item_name+' - '+value.location_name+'</option>';                   
                        });
                        
                      html += '</select>'+
                    '</td>'+ 
                    '<td><input type="number" name="qty[]" id="qty_'+row_id+'" class="form-control" onkeyup="getTotal('+row_id+')"></td>'+
                    '<td><input type="text" name="rate[]" id="rate_'+row_id+'" class="form-control" onkeyup="getTotal('+row_id+')"></td>'+
                    '<td><input type="text" name="amount[]" style="text-align:right;" id="amount_'+row_id+'" class="form-control" disabled><input type="hidden" name="amount_value[]" id="amount_value_'+row_id+'" class="form-control"></td>'+
                    '<td><button type="button" class="btn btn-default" onclick="removeRow(\''+row_id+'\')"><i class="fa fa-close"></i></button></td>'+
                    '</tr>';

                if(count_table_tbody_tr >= 1) {
                $("#item_info_table tbody tr:last").after(html);  
              }
              else {
                $("#item_info_table tbody").html(html);
              }

              $(".item").select2();

          }
        });

      return false;
    });

  }); // /document

   

  function getTotal(row = null) {
    if(row) {
      var total = Number($("#rate_"+row).val()) * Number($("#qty_"+row).val());
      total = total.toFixed(2);
      $("#amount_"+row).val(total);
      $("#amount_value_"+row).val(total);
      
      subAmount();

    } else {
      alert('no row !! please refresh the page');
    }
  }



  // get the item information from the server
  function getItemData(row_id)
  {
    var item_location_id = $("#item_"+row_id).val();  

    if(item_location_id == "") {
      $("#rate_"+row_id).val("");
      $("#rate_"+row_id).val("");

      $("#qty_"+row_id).val("");           

      $("#amount_"+row_id).val("");
      $("#amount_value_"+row_id).val("");

    } else {
      $.ajax({
        url: base_url + 'order/getItemPrice',
        type: 'post',
        data: {item_location_id : item_location_id},
        dataType: 'json',
        success:function(response) {
          // setting the rate value into the rate input field
          
          $("#rate_"+row_id).val(response.item_price);

          $("#qty_"+row_id).val(1);
          $("#qty_value_"+row_id).val(1);

          var total = Number(response.item_price) * 1;
          total = total.toFixed(2);
          $("#amount_"+row_id).val(total);
          $("#amount_value_"+row_id).val(total);
          
          subAmount();
        } // /success
      }); // /ajax function to fetch the item data 
    }
  }



  // calculate the total amount of the order
  function subAmount() {
    
    var previous_balance = <?php echo $order_data['order']['previous_balance'] ?>;

    var tableItemLength = $("#item_info_table tbody tr").length;
    var totalSubAmount = 0;
    for(x = 0; x < tableItemLength; x++) {
      var tr = $("#item_info_table tbody tr")[x];
      var count = $(tr).attr('id');
      count = count.substring(4);

      totalSubAmount = Number(totalSubAmount) + Number($("#amount_"+count).val());
    } // /for

    totalSubAmount = totalSubAmount.toFixed(2);     
    
    $("#order_total").val(totalSubAmount);

    // new balance
    var amount_due = Number(previous_balance) + Number(totalSubAmount) ;
    amount_due = amount_due.toFixed(2);
    $("#amount_due").val(amount_due);

    

  } // /sub total amount



  function removeRow(tr_id)
  {
    $("#item_info_table tbody tr#row_"+tr_id).remove();
    subAmount();
  }
</script>