<div class="content-wrapper">

  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('user') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">User</li>
    </ol>
  </section>

  <br>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

       <!-- Main content -->
    <section class="content">

    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        U S E R                                                 -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        




      <div class="box">
          <form role="form" action="<?php base_url('user/update') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>  

                 <div class="row">

                  <div class="form-group">
            <div class="alert alert-info alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                Leave the password field empty if you don't want to change.
            </div>
          </div> 

                  <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="username">Username <font color="red">*</font></label>
                      <input type="text" class="form-control" id="username" name="username" autocomplete="off"
                      value="<?php echo set_value('username', isset($user_data['username']) ? $user_data['username'] : ''); ?>" />
                    </div>
                  </div>  
				  
				          <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="password">Password <font color="red">*</font></label>
                      <input type="text" class="form-control" id="password" name="password" autocomplete="off">
                    </div>
                  </div>

                  <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="cpassword">Confirm Password<font color="red"> *</font></label>
                      <input type="password" class="form-control" id="cpassword" name="cpassword" autocomplete="off">
                    </div>
                  </div>

                  <div class="col-md-4 col-xs-4">    
                    <div class="form-group">
                      <label for="user_name">Name <font color="red">*</font></label>
                      <input type="text" class="form-control" id="user_name" name="user_name" autocomplete="off"
                      value="<?php echo set_value('user_name', isset($user_data['user_name']) ? $user_data['user_name'] : ''); ?>" />
                    </div>
                 </div> 

                <div class="col-md-2 col-xs-2" align="center">
                    <div class="radio">
                      <label><input type="radio" name="active" id="active" class="" <?php if($user_data['active']=='1') echo "checked='checked'"; ?> value="1" <?php echo $this->form_validation->set_radio('active', 1); ?> />Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                      <label><input type="radio" name="active" id="active" class="" <?php if($user_data['active']=='2') echo "checked='checked'"; ?> value="2" <?php echo $this->form_validation->set_radio('active', 2); ?> />Inactive</label> 
                    </div>
                  </div>
                </div>   


                <div class="row">

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="profile">Profile <font color="red">*</font></label>
                      <select class="form-control select_group" id="profile" name="profile">
                        <option value=""></option> 
                        <?php foreach ($profile as $k => $v): ?>
                          <option value="<?php echo $v['profile_id'] ?>" 
                          <?php if(set_value('profile', isset($user_data['profile_fk']) ? $user_data['profile_fk'] : '') == $v['profile_id']) { echo "selected='selected'"; } ?> >
                          <?php echo $v['profile_name'] ?>                            
                          </option>
                        <?php endforeach ?>
                      </select>
                    </div>
                  </div>
                  
                    
                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="phone">Phone</label>
                      <input type="text" class="form-control" id="phone" name="phone" autocomplete="off" 
                      value="<?php echo set_value('phone', isset($user_data['phone']) ? $user_data['phone'] : ''); ?>" />
                    </div>
                  </div>  
				  
                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="email">Email <font color="red">*</font></label>
                      <input type="text" class="form-control" id="email" name="email" autocomplete="off" 
                      value="<?php echo set_value('email', isset($user_data['email']) ? $user_data['email'] : ''); ?>" />
                    </div>
                  </div>  

				  </div>
  				  
 

              
                <div class="row">  
        
                  <div class="col-md-12 col-xs-12">
                     <div class="form-group">
                      <label for="remark">Remark</label>
                      <textarea type="text" class="form-control" rows="5" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark', isset($user_data['remark']) ? $user_data['remark'] : ''); ?></textarea>
                    </div>
                  </div>  
                </div>  
                
              </div>    <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="<?php echo base_url('user/') ?>" class="btn btn-warning">Back</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>



