<div class="content-wrapper">
  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('delivery') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Delivery</li>
    </ol>
    <br>
  </section>


<section class="content">
    <div class="row">
      <div class="col-md-12 col-xs-12">


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        

  <div id="messages"></div>

  <?php if($this->session->flashdata('success')): ?>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <?php echo $this->session->flashdata('success'); ?>
    </div>
  <?php elseif($this->session->flashdata('error')): ?>
    <div class="alert alert-error alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <?php echo $this->session->flashdata('error'); ?>
    </div>
  <?php endif; ?>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                     C R E A T E                                                 -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


<form role="form" action="<?php base_url('delivery/create') ?>" method="post" enctype="multipart/form-data" >

  <?php echo validation_errors(); ?> 

  <div class="box">

    <div class="box-body">

        <div class="row">

          <div class="col-md-10 col-xs-10">
           <h4 class="box-title">Add Delivery </h4>
          </div>

          <div class="col-md-2 col-xs-2">
            <div class="form-group" style="display: flex">
              <label for="delivery_no">Delivery No <?php echo $generate_no['next_no'] ?></label> 
              <input type="hidden" class="form-control" id="delivery_no" name="delivery_no" autocomplete="off" 
                value="<?php echo $generate_no['next_no'] ?>" />

            </div>
           </div>
        </div>
     
        <div class="row">          

          <div class="col-md-4 col-xs-4">    
            <div class="form-group">
              <label for="supplier">Supplier<font color="red"> *</font></label>
              <select class="form-control select_group" id="supplier" name="supplier">

                <!-- Create can come from the main menu or from the supplier edit page.  
                     When it comes from edit supplier, we have the supplier id and can present the supplier -->  

                <?php if(empty($this->session->userdata('supplier_id'))): ?>  
                   <option value=""></option> 
                  <?php foreach ($supplier as $k => $v): ?>
                  <option value="<?php echo $v['supplier_id'] ?>" <?php echo set_select('supplier', $v['supplier_id']); ?>><?php echo $v['supplier_name'] ?></option>
                <?php endforeach ?> 
                  
                <?php else : ?>                 
                   <?php foreach ($supplier as $k => $v): ?>
                    <option value="<?php echo $v['supplier_id'] ?>" <?php if($this->session->userdata('supplier_id') == $v['supplier_id']) { echo "selected='selected'"; } ?> ><?php echo $v['supplier_name'] ?></option>
                   <?php endforeach ?>
                <?php endif; ?>                

              </select>
            </div>
          </div>

          <div class="col-md-2 col-xs-2"> </div>

          <div class="col-md-2 col-xs-2">
            <div class="form-group">
              <label for="delivery_date">Delivery Date <font color="red"> *</font></label>
              <input type="date" class="form-control" id="delivery_date" name="delivery_date" autocomplete="off" 
              value="<?php echo date('Y-m-d');?>"/>
            </div>
          </div>

           <div class="col-md-2 col-xs-2">
            <div class="form-group">
              <label for="production_date">Production Date</label>
              <input type="date" class="form-control" id="production_date" name="production_date" autocomplete="off" 
              value="<?php echo date('Y-m-d');?>"/>
            </div>
          </div>

           <div class="col-md-2 col-xs-2">
            <div class="form-group">
              <label for="expiry_date">Expiry Date</label>
              <input type="date" class="form-control" id="expiry_date" name="expiry_date" autocomplete="off" 
              value="<?php echo date('Y-m-d');?>"/>
            </div>
          </div>

          </div>    

          <div class="row">
            
            <div class="col-md-2 col-xs-2">
              <div class="form-group">
                <label for="batch_no">Batch No</label>
                <input type="text" class="form-control" id="batch_no" name="batch_no" autocomplete="off" value="<?php echo set_value('batch_no'); ?>"/>
             </div>
           </div>

              <div class="col-md-2 col-xs-2">
              <div class="form-group">
                <label for="lot_no">Lot No</label>
                <input type="text" class="form-control" id="lot_no" name="lot_no" autocomplete="off" value="<?php echo set_value('lot_no'); ?>"/>
             </div>
           </div>

            <div class="col-md-2 col-xs-2">
              <div class="form-group">
                <label for="reference_no">Reference No</label>
                <input type="text" class="form-control" id="reference_no" name="reference_no" autocomplete="off" value="<?php echo set_value('reference_no'); ?>"/>
             </div>
            </div>

            <div class="col-md-6 col-xs-6">
               <div class="form-group">
                <label for="disposition">Disposition</label>
                <textarea type="text" class="form-control" rows="3" id="disposition" name="disposition" autocomplete="off"><?php echo set_value('disposition'); ?></textarea>
              </div>
            </div> 

          </div>  
          
          <br /> 
          <table class="table table-border" id="item_info_table">
            <thead>
              <tr>
                <th style="width:50%">Item <font color="red"> *</font></th>
                <th style="width:10%">Qty</th>
                <th style="width:10%">Rate</th>
                <th style="width:10%"><button type="button" id="add_row" class="btn btn-default"><i class="fa fa-plus"></i></button></th>
              </tr>
            </thead>

             <tbody>
               <tr id="row_1">
                 <td>
                  <select class="form-control select_group item" data-row-id="row_1" id="item_1" name="item[]" style="width:100%;" onchange="getItemData(1)" required>
                      <option value=""></option>
                      <?php foreach ($item as $k => $v): ?>
                        <option value="<?php echo $v['item_location_id'] ?>">(<?php echo $v['item_code'] ?>) <?php echo $v['item_name'] ?> - <?php echo $v['location_name'] ?></option>
                      <?php endforeach ?>
                    </select>
                  </td>
                  <td><input type="text" name="qty[]" id="qty_1" class="form-control" required ></td>
                  <td><input type="text" name="rate[]" id="rate_1" class="form-control"></td>
                  <td><button type="button" class="btn btn-default" onclick="removeRow('1')"><i class="fa fa-close"></i></button></td>
               </tr>
             </tbody>
          </table>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Save</button>
          <a href="<?php echo base_url('delivery/') ?>" class="btn btn-warning">Back</a>
        </div>
      </form>
  </div>
</div>
</div>


</section>
</div>



<!------------------------------------------------------------->
<!-- Javascript part of Delivery                            --->
<!------------------------------------------------------------->

<script type="text/javascript">
  var base_url = "<?php echo base_url(); ?>";

  $(document).ready(function() {
    $(".select_group").select2();

    
    var btnCust = '<button type="button" class="btn btn-secondary" title="Add picture tags" ' + 
        'onclick="alert(\'Call your custom code here.\')">' +
        '<i class="glyphicon glyphicon-tag"></i>' +
        '</button>'; 
  
    // Add new row in the table 
    $("#add_row").unbind('click').bind('click', function() {
      var table = $("#item_info_table");
      var count_table_tbody_tr = $("#item_info_table tbody tr").length;
      var row_id = count_table_tbody_tr + 1;

      $.ajax({
          url: base_url + '/delivery/getItemLocationData/',
          type: 'post',
          dataType: 'json',
          success:function(response) {
            
              // console.log(reponse.x);
               var html = '<tr id="row_'+row_id+'">'+
                   '<td>'+ 
                    '<select class="form-control select_group item" data-row-id="'+row_id+'" id="item_'+row_id+'" name="item[]" style="width:100%;" onchange="getItemData('+row_id+')">'+
                        '<option value=""></option>';
                        $.each(response, function(index, value) {
                          html += '<option value="'+value.item_location_id+'">'+'('+value.item_code+') '+value.item_name+' - '+value.location_name+'</option>';                   
                        });
                        
                      html += '</select>'+
                    '</td>'+ 
                    '<td><input type="text" name="qty[]" id="qty_'+row_id+'" class="form-control" ></td>'+
                    '<td><input type="text" name="rate[]" id="rate_'+row_id+'" class="form-control" ></td>'+
                    '<td><button type="button" class="btn btn-default" onclick="removeRow(\''+row_id+'\')"><i class="fa fa-close"></i></button></td>'+
                    '</tr>';

                if(count_table_tbody_tr >= 1) {
                $("#item_info_table tbody tr:last").after(html);  
              }
              else {
                $("#item_info_table tbody").html(html);
              }

              $(".item").select2();

          }
        });

      return false;
    });

  }); 

 

  function getItemData(row_id)
  {
    var item_location_id = $("#item_"+row_id).val(); 

    if(item_location_id == "") {
      $("#rate_"+row_id).val("");
      $("#qty_"+row_id).val("");      

    } else {
      $.ajax({
        url: base_url + 'order/getItemPrice',
        type: 'post',
        data: {item_location_id : item_location_id},
        dataType: 'json',
        success:function(response) {
          // setting the rate value into the rate input field          
          $("#rate_"+row_id).val(response.item_price);
          $("#qty_"+row_id).val(1);          
        } // /success
      }); // /ajax function to fetch the item data 
    }
  }
  

  function removeRow(tr_id)
  {
    $("#item_info_table tbody tr#row_"+tr_id).remove();
    
  }
</script>