<div class="content-wrapper">
  <section class="content-header">
    <h1>Suppliers Deliveries</h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Suppliers Deliveries</li>
    </ol>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-md-12 col-xs-12">


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        

  <div id="messages"></div>

  <?php if($this->session->flashdata('success')): ?>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <?php echo $this->session->flashdata('success'); ?>
    </div>
  <?php elseif($this->session->flashdata('error')): ?>
    <div class="alert alert-error alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <?php echo $this->session->flashdata('error'); ?>
    </div>
  <?php endif; ?>


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        V I E W                                                  -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->  

  

   <div class="row">  
      <div class="col-md-12 col-xs-12">
        <div class="box">
          <div class="box-body">  

            <?php if(in_array('createDelivery', $user_permission)): ?>
                 <a href="<?php echo base_url('delivery/create') ?>" class="btn btn-primary">Add Delivery</a>    
             <?php endif; ?>

            <div class="form-group pull-right">
              <label class="margin-r-5" for="date_to">To</label>
              <input type="date" class="custom-date-filter form-control" id="date_to" name="date_to" autocomplete="off" value="<?php echo date('Y-m-d');?>"/>
            </div>

            <div class="form-group pull-right margin-r-5">
              <label class="margin-r-5" for="date_from">Date From</label>
              <input type="date" class="custom-date-filter form-control" id="date_from" name="date_from" autocomplete="off" value="<?php $date = date_create(date('Y-m-d')); 
                    date_sub($date,date_interval_create_from_date_string("90 days"));
                    echo date_format($date, 'Y-m-d'); ?>"/>

            </div>

            <div class="form-group pull-right margin-r-5">
              <div class="form-group">
                <label for="supplier">Supplier</label>
                <select class="custom-supplier-filter form-control" id="supplier" name="supplier" autocomplete="off">
                   <option value="all">All Suppliers</option>
                    <?php foreach ($supplier as $k => $v): ?>
                    <option value="<?php echo $v['supplier_id'] ?>" <?php echo set_select('supplier_fk', $v['supplier_id']); ?>><?php echo $v['supplier_name'] ?></option>
                    <?php endforeach ?>
                  </select>
              </div>
            </div>

            <table id="manageTable" class="table table-bdeliveryed table-striped" style="width:100%">
              <thead>
              <tr>
                <th width="2%">Delivery No</th>  
                <th width="20%">Supplier</th>                             
                <th width="7%">Delivery Date</th>
                <th width="7%">Production Date</th> 
                <th width="7%">Expiry Date</th> 
                <th width="7%">Batch No</th>
                <th width="7%">Lot No</th>
                <th width="7%">Reference No</th>
                <?php if(in_array('updateDelivery', $user_permission) || in_array('viewDelivery', $user_permission) || in_array('deleteDelivery', $user_permission)): ?>
                  <th width="12%">Action</th>
                <?php endif; ?>
              </tr>
              </thead>

            </table>
          </div>
        </div>
      </div>
    </div> 

  </section>

</div>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                   D E L E T E                                                   -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

<?php if(in_array('deleteDelivery', $user_permission)): ?>

  <div class="modal fade" tabindex="-1" role="dialog" id="removeModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete Delivery</h4>
      </div>

      <form role="form" action="<?php echo base_url('delivery/remove') ?>" method="post" id="removeForm">
        <div class="modal-body">         
          <p>Do you really want to delete the delivery?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Delete</button>
        </div>
      </form>


    </div>
  </div>
</div>


<?php endif; ?>



<!------------------------------------------------------------->
<!-- Javascript part of Delivery                            --->
<!------------------------------------------------------------->


<script type="text/javascript">
var manageTable;
var base_url = "<?php echo base_url(); ?>";

$(document).ready(function() {


  //THE DATE FILTER CONTROLS
  var $dateFilter = $('.custom-date-filter');


  // initialize the datatable 
  manageTable = $('#manageTable').DataTable({
    'ajax': {url: base_url + 'delivery/fetchDeliveryDataByDate/',
      data:
        {
          'date_from': $('[name="date_from"]').val(),
          'date_to': $('[name="date_to"]').val(),
          'supplier': $('[name="supplier"]').val(),
        }
      },
       
    'order': [],    
    'lengthMenu': [[100, -1], [100, "All"]],
      dom:  "<'row'<'col-sm-3'l><'col-sm-6'B><'col-sm-3'f>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-5'i><'col-sm-7'p>>",
      buttons: [
                {extend: 'excel',exportOptions: {columns: ':visible',rows: ':visible'}},
                {extend: 'pdf',pageSize: 'LEGAL',orientation: 'landscape',exportOptions: {columns: ':visible',}},
                {extend: 'print',exportOptions: {columns: ':visible',rows: ':visible'}},
                'colvis' 
                ]     

    });





  //RELOAD TABLE ON CHANGE OF FILTERS
  $dateFilter.on('change', function (e) {
    manageTable.destroy();
     manageTable = $('#manageTable').DataTable({
    'ajax': {url: base_url + 'delivery/fetchDeliveryDataByDate/',
    data:
      {
        'date_from': $('[name="date_from"]').val(),
        'date_to': $('[name="date_to"]').val(),
        'supplier': $('[name="supplier"]').val(),
      }
      },
  
    'order': [],    
    'lengthMenu': [[100, -1], [100, "All"]],
      dom:  "<'row'<'col-sm-3'l><'col-sm-6'B><'col-sm-3'f>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-5'i><'col-sm-7'p>>",
      buttons: [
                {extend: 'excel',exportOptions: {columns: ':visible',rows: ':visible'}},
                {extend: 'pdf',pageSize: 'LEGAL',orientation: 'landscape',exportOptions: {columns: ':visible',}},
                {extend: 'print',exportOptions: {columns: ':visible',rows: ':visible'}},
                'colvis' 
                ]     

    });
  });


  //THE AREA FILTER CONTROLS
  var $supplierFilter = $('.custom-supplier-filter');
  manageTable.destroy();
  manageTable = $('#manageTable').DataTable({
    'ajax': {url: base_url + 'delivery/fetchDeliveryDataByDate/',
    data:
      {
        'date_from': $('[name="date_from"]').val(),
        'date_to': $('[name="date_to"]').val(),
        'supplier': $('[name="supplier"]').val(),
      }
      },
    'order':  [],
    'lengthMenu': [[100, -1], [100, "All"]],
      dom:  "<'row'<'col-sm-3'l><'col-sm-6'B><'col-sm-3'f>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-5'i><'col-sm-7'p>>",
      buttons: [
                {extend: 'excel',exportOptions: {columns: ':visible',rows: ':visible'}},
                {extend: 'pdf',pageSize: 'LEGAL',orientation: 'landscape',exportOptions: {columns: ':visible',}},
                {extend: 'print',exportOptions: {columns: ':visible',rows: ':visible'}},
                'colvis' 
                ]    
  });

  //RELOAD TABLE ON CHANGE OF FILTERS
  $supplierFilter.on('change', function (e) {

    manageTable.destroy();

    manageTable = $('#manageTable').DataTable({
      'ajax': {url: base_url + 'delivery/fetchDeliveryDataByDate/',
    data:
      {
        'date_from': $('[name="date_from"]').val(),
        'date_to': $('[name="date_to"]').val(),
        'supplier': $('[name="supplier"]').val(),
      }
      },
     'order': [],
     'lengthMenu': [[100, -1], [100, "All"]],
      dom:  "<'row'<'col-sm-3'l><'col-sm-6'B><'col-sm-3'f>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-5'i><'col-sm-7'p>>",
      buttons: [
                {extend: 'excel',exportOptions: {columns: ':visible',rows: ':visible'}},
                {extend: 'pdf',pageSize: 'LEGAL',orientation: 'landscape',exportOptions: {columns: ':visible',}},
                {extend: 'print',exportOptions: {columns: ':visible',rows: ':visible'}},
                'colvis' 
                ]    
    });

  });
   

});



// remove functions 
function removeFunc(delivery_id)
{
  if(delivery_id) {
    $("#removeForm").on('submit', function() {

      var form = $(this);

      // remove the text-danger
      $(".text-danger").remove();

      $.ajax({
        url: form.attr('action'),
        type: form.attr('method'),
        data: { delivery_id }, 
        dataType: 'json',
        success:function(response) {

          manageTable.ajax.reload(null, false); 

          if(response.success === true) {
            $("#messages").html('<div class="alert alert-success alert-dismissible" role="alert">'+
              '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
              '<strong> <span class="glyphicon glyphicon-ok-sign"></span> </strong>'+response.messages+
            '</div>');           

          } else {

            $("#messages").html('<div class="alert alert-warning alert-dismissible" role="alert">'+
              '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
              '<strong> <span class="glyphicon glyphicon-exclamation-sign"></span> </strong>'+response.messages+
            '</div>'); 
          }

           // hide the modal
            $("#removeModal").modal('hide');
        }
      }); 

      return false;
    });
  }
}


</script>
