<div class="content-wrapper">
  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('asset') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Asset</li>
    </ol>
    <br>
  </section>


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

  <section class="content">
    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                   A D D    A s s e t                                            -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->  

        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Add Asset</h3>
          </div>
          <form role="form" action="<?php base_url('asset/create') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>

                   
                <div class="row">
                  <div class="col-md-7 col-xs-7">
                    <div class="form-group">
                      <label for="asset_name">Asset name <font color="red">*</font></label>
                      <input type="text" class="form-control" id="asset_name" name="asset_name"  autocomplete="off" 
                      value="<?php echo set_value('asset_name'); ?>"/>
                    </div>
                </div>  

                
                 <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="asset_code">Asset Code</label>
                      <input type="text" class="form-control" id="asset_code" name="asset_code" autocomplete="off" 
                      value="<?php echo set_value('asset_code'); ?>"/>
                    </div>
                  </div>  

                <div class="col-md-2 col-xs-2">                     
                     <div class="form-group">
                        <label for="availability">Availability</label>
                        <select class="form-control select_group" id="availability" name="availability">
                           <option value=""></option> 
                          <?php foreach ($availability as $k => $v): ?>
                          <option value="<?php echo $v['availability_id'] ?>" <?php echo set_select('availability', $v['availability_id']); ?>><?php echo $v['availability_name'] ?></option>
                          <?php endforeach ?>
                        </select>
                    </div>  
                  </div>                   

                </div>
               

                <div class="row"> 

                  <div class="col-md-3 col-xs-3">                     
                     <div class="form-group">
                        <label for="asset_type">Asset Type</label>
                        <select class="form-control select_group" id="asset_type" name="asset_type">
                           <option value=""></option> 
                          <?php foreach ($asset_type as $k => $v): ?>
                          <option value="<?php echo $v['asset_type_id'] ?>" <?php echo set_select('asset_type', $v['asset_type_id']); ?>><?php echo $v['asset_type_name'] ?></option>
                          <?php endforeach ?>
                        </select>
                    </div>  
                  </div>  

                   <div class="col-md-3 col-xs-3">
                      <div class="form-group">
                        <label for="brand">Brand</label>
                        <input type="text" class="form-control" id="brand" name="brand"  autocomplete="off" 
                        value="<?php echo set_value('brand'); ?>"/>
                      </div>
                  </div> 
                      

                   <div class="col-md-3 col-xs-3">                     
                     <div class="form-group">
                        <label for="location">Location</label>
                        <select class="form-control select_group" id="location" name="location">
                          <option value=""></option> 
                          <?php foreach ($location as $k => $v): ?>
                          <option value="<?php echo $v['location_id'] ?>" <?php echo set_select('location', $v['location_id']); ?>><?php echo $v['location_name'] ?></option>
                          <?php endforeach ?>
                        </select>
                    </div>  
                  </div> 

                   <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="serial_number">Serial number</label>
                      <input type="text" class="form-control" id="serial_number" name="serial_number" autocomplete="off" 
                      value="<?php echo set_value('serial_number'); ?>"/>
                    </div>
                  </div>   
                     
              </div>  

               <div class="row">               

                  <div class="col-md-3 col-xs-3">
                      <div class="form-group">
                        <label for="acquisition_date">Acquisition Date</label>
                        <input type="date" class="form-control" id="acquisition_date" name="acquisition_date" autocomplete="off" 
                        value="<?php echo set_value('acquisition_date'); ?>"/>
                      </div>
                    </div> 

                <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="expiration_date">Expiration date</label>
                      <input type="date" class="form-control" id="expiration_date" name="expiration_date"  autocomplete="off" 
                      value="<?php echo set_value('expiration_date'); ?>"/>
                    </div>
                </div> 

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="asset_quantity">Quantity</label>
                      <input type="text" class="form-control" id="asset_quantity" name="asset_quantity" autocomplete="off" 
                      value="<?php echo set_value('asset_quantity'); ?>"/>
                    </div>
                  </div> 

                   <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="asset_value">Value <font color="red">*</font></label>
                      <input type="text" class="form-control" id="asset_value" name="asset_value" autocomplete="off" 
                      value="<?php echo set_value('asset_value'); ?>"/>
                    </div>
                  </div>     

                  </div>
               

                <div class="row">       

                  <div class="col-md-6 col-xs-6">
                    <div class="form-group">
                      <label for="description">Description</label>
                      <textarea type="text" class="form-control" rows="3" id="description" name="description" autocomplete="off"><?php echo set_value('description'); ?></textarea>
                    </div>
                  </div>  
        
                  <div class="col-md-6 col-xs-6">
                     <div class="form-group">
                      <label for="remark">Remark</label>
                      <textarea type="text" class="form-control" rows="3" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark'); ?></textarea>
                    </div>
                  </div>  
                </div>                        
                  
              </div>

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="<?php echo base_url('asset/') ?>" class="btn btn-warning">Back</a>
              </div> 
            </div>
          </form>
        </div>
      </div>
    </div>    

  </section>
</div>




<!-----------------------------------------------   Javascript  ---------------------------------------------------------------->


<script type="text/javascript">

    $(".select_group").select2();
  //  $("#description").wysihtml5();

</script>
    
   
  