<div class="content-wrapper">

  <section class="content-header">
    <h1>Update Asset <?php echo $asset_data['asset_code'];?></h1></h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('asset') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Asset</li>
    </ol>
  </section>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                       Tab section                                               -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

  <section class="content">
    <ul class="nav nav-tabs">
      <li class="<?php echo (($active_tab === 'asset') ? 'active' : '')?>"><a data-toggle="tab" href="#asset">Asset</a></li>

      <li class="<?php echo (($active_tab === 'maintenance') ? 'active' : '')?>"><a data-toggle="tab" href="#maintenance">Maintenance</a></li>
      <li class="<?php echo (($active_tab === 'document') ? 'active' : '')?>"><a data-toggle="tab" href="#document">Document</a></li>
    </ul>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        Session variables                                        -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


    <!-- Creation of a session field to keep the asset id -->
    <?php $this->session->unset_userdata('asset_id');?>         
    <?php if(empty($this->session->userdata('asset_id'))) {
      $asset_id = array('asset_id' => $asset_data['asset_id']);
      $this->session->set_userdata($asset_id);} ?>  

    <!-- Creation of a session to keep the directory for the manipulation
              of upload of documents -->

    <?php $this->session->unset_userdata('directory');?>             
    <?php if(empty($this->session->userdata('directory'))) {
            $directory = array('directory' => '/upload/assets/'.$asset_data['asset_id'].'/');
            $this->session->set_userdata($directory);
      } ?>   






<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 



    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

       <?php if($this->session->flashdata('success')): ?>
          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
      <?php elseif ($this->session->flashdata('error')) : ?>
        <div class="alert alert-error alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <?php echo $this->session->flashdata('error'); ?>
        </div>
      <?php elseif ($this->session->flashdata('warning')) : ?>
        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <?php echo $this->session->flashdata('warning'); ?>
        </div>
      <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        A S S E T                                                -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        



<div id="asset" class="tab-pane fade <?php echo (($active_tab === 'asset') ? 'in active' : '') ?>">
  <div class="box">
      <form role="form" action="<?php base_url('asset/update') ?>" method="post" enctype="multipart/form-data">
          <div class="box-body">

            <?php echo validation_errors(); ?>  

             <div class="row">                

              <div class="col-md-7 col-xs-7">    
                <div class="form-group">
                  <label for="asset_name">Asset name <font color="red">*</font></label>
                  <input type="text" class="form-control" id="asset_name" name="asset_name" autocomplete="off"
                  value="<?php echo set_value('asset_name', isset($asset_data['asset_name']) ? $asset_data['asset_name'] : ''); ?>" />
                </div>
             </div> 

              <div class="col-md-2 col-xs-2">
                <div class="form-group">
                  <label for="asset_code">Asset Code</font></label>
                  <input type="text" class="form-control" id="asset_code" name="asset_code" autocomplete="off"
                  value="<?php echo set_value('asset_code', isset($asset_data['asset_code']) ? $asset_data['asset_code'] : ''); ?>" />
                </div>
              </div>

             <div class="col-md-2 col-xs-2">
                <div class="form-group">
                  <label for="availability">Availability</label>
                  <select class="form-control select_group" id="availability" name="availability">
                    <option value=""></option> 
                    <?php foreach ($availability as $k => $v): ?>
                      <option value="<?php echo $v['availability_id'] ?>" <?php if($asset_data['availability_fk'] == $v['availability_id']) { echo "selected='selected'"; } ?> ><?php echo $v['availability_name'] ?></option>
                    <?php endforeach ?>
                 </select>
                </div>
              </div>

            </div>   
            
              <div class="row">

                <div class="col-md-3 col-xs-3">
                <div class="form-group">
                  <label for="asset_type">Asset Type</label>
                  <select class="form-control select_group" id="asset_type" name="asset_type">
                    <option value=""></option> 
                    <?php foreach ($asset_type as $k => $v): ?>
                      <option value="<?php echo $v['asset_type_id'] ?>" <?php if($asset_data['asset_type_fk'] == $v['asset_type_id']) { echo "selected='selected'"; } ?> ><?php echo $v['asset_type_name'] ?></option>
                    <?php endforeach ?>
                 </select>
                </div>
              </div>

              <div class="col-md-3 col-xs-3">    
                <div class="form-group">
                  <label for="asset_name">Brand</label>
                  <input type="text" class="form-control" id="brand" name="brand" autocomplete="off"
                  value="<?php echo set_value('brand', isset($asset_data['brand']) ? $asset_data['brand'] : ''); ?>" />
                </div>
             </div> 

                 <div class="col-md-3 col-xs-3">
                <div class="form-group">
                  <label for="location">Location</label>
                  <select class="form-control select_group" id="location" name="location">
                    <option value=""></option> 
                    <?php foreach ($location as $k => $v): ?>
                      <option value="<?php echo $v['location_id'] ?>" <?php if($asset_data['location_fk'] == $v['location_id']) { echo "selected='selected'"; } ?> ><?php echo $v['location_name'] ?></option>
                    <?php endforeach ?>
                 </select>
                </div>
              </div>


                <div class="col-md-3 col-xs-3">
                  <div class="form-group">
                    <label for="serial_number">Serial Number</label>
                    <input type="text" class="form-control" id="serial_number" name="serial_number" autocomplete="off" 
                    value="<?php echo set_value('serial_number', isset($asset_data['serial_number']) ? $asset_data['serial_number'] : ''); ?>" />
                  </div>
                </div> 

                

              </div>


             <div class="row">    

              
              <div class="col-md-3 col-xs-3">
                <div class="form-group">
                  <label for="acquisition_date">Acquisition Date</label>
                  <input type="date" class="form-control" id="acquisition_date" name="acquisition_date" autocomplete="off" 
                  value="<?php echo set_value('acquisition_date', isset($asset_data['acquisition_date']) ? $asset_data['acquisition_date'] : ''); ?>" />
                </div>
              </div>  

              <div class="col-md-3 col-xs-3">
                  <div class="form-group">
                    <label for="expiration_date">Expiration Date</label>
                    <input type="date" class="form-control" id="expiration_date" name="expiration_date" autocomplete="off" 
                    value="<?php echo set_value('expiration_date', isset($asset_data['expiration_date']) ? $asset_data['expiration_date'] : ''); ?>" />
                  </div>
                </div>   

              <div class="col-md-3 col-xs-3">
                  <div class="form-group">
                    <label for="asset_quantity">Quantity</label>
                    <input type="text" class="form-control" id="asset_quantity" name="asset_quantity" autocomplete="off" 
                    value="<?php echo set_value('asset_quantity', isset($asset_data['asset_quantity']) ? $asset_data['asset_quantity'] : ''); ?>" />
                  </div>
                </div>  

                <div class="col-md-3 col-xs-3">
                <div class="form-group">
                  <label for="asset_value">Value <font color="red">*</font></label>
                  <input type="text" class="form-control" id="asset_value" name="asset_value" autocomplete="off" 
                  value="<?php echo set_value('asset_value', isset($asset_data['asset_value']) ? $asset_data['asset_value'] : ''); ?>" />
                </div>
              </div>             


            </div>                
          
            <div class="row">       

              <div class="col-md-6 col-xs-6">
                <div class="form-group">
                  <label for="description">Description</label>
                  <textarea type="text" class="form-control" rows="3" id="description" name="description" autocomplete="off"><?php echo set_value('description', isset($asset_data['description']) ? $asset_data['description'] : ''); ?></textarea>
                </div>
              </div>  
    
              <div class="col-md-6 col-xs-6">
                 <div class="form-group">
                  <label for="remark">Remark</label>
                  <textarea type="text" class="form-control" rows="3" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark', isset($asset_data['remark']) ? $asset_data['remark'] : ''); ?></textarea>
                </div>
              </div>  
            </div>  
            
          </div>    <!-- /.box-body -->

          <div class="box-footer">
            <button type="submit" class="btn btn-primary">Save</button>
            <?php echo '<a href="'.base_url('report_asset/report_asset/'.$asset_data['asset_id']).'" target="_blank" class="btn btn-success"><i class="fa fa-print" ></i></a>'; ?>
            <a href="<?php echo base_url('asset/') ?>" class="btn btn-warning">Back</a>
          </div>

        </form>
    </div>
  </div>
     



<!------------------------------------------------------------->
<!-- Javascript part of Asset                          --->
<!------------------------------------------------------------->

<script type="text/javascript">  

    $(".select_group").select2({width: '100%'});

    
</script>


<!------------------------------------------------------------->
<!-- Load part of codes for maintenance and document        --->
<!------------------------------------------------------------->

<?php $this->load->view('asset/maintenance'); ?>

<?php $this->load->view('asset/document'); ?>




