<div class="content-wrapper">
  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('supplier') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Add Supplier</li>
    </ol>
    <br>
  </section>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


  <section class="content">
    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                   A D D    S U P P L I E R                                      -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->


  <div class="box">
    <div class="box-header">
      <h4 class="box-title">Add Supplier</h4>
    </div>
    <form role="form" action="<?php base_url('supplier/create') ?>" method="post" enctype="multipart/form-data">
        <div class="box-body">

          <?php echo validation_errors(); ?>

       <div class="row">                  

          <div class="col-md-6 col-xs-6">
            <div class="form-group">
              <label for="supplier_name">Name <font color="red">*</font></label>
              <input type="text" class="form-control" id="supplier_name" name="supplier_name"  autocomplete="off" 
              value="<?php echo set_value('supplier_name'); ?>"/>
            </div>
          </div>
		  
		      <div class="col-md-4 col-xs-4">
            <div class="form-group">
              <label for="tin">TIN</label>
              <input type="text" class="form-control" id="tin" name="tin"  autocomplete="off" 
              value="<?php echo set_value('tin'); ?>"/>
            </div>
          </div>

          <div class="col-md-2 col-xs-2" align="center">
            <div class="form-group">
            <div class="radio">
                <label><input type="radio" name="active" id="active" value="1" checked="checked" >Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <label><input type="radio" name="active" id="active" value="2" >Inactive</label>
            </div>
          </div> 
        </div>
		
        </div>  

        <div class="row">          

          <div class="col-md-5 col-xs-5">
            <div class="form-group">
              <label for="address">Address</label>
              <input type="text" class="form-control" id="address" name="address"  autocomplete="off" 
              value="<?php echo set_value('address'); ?>"/>
            </div>
          </div>
		  
		    <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="website">Website</label>
              <input type="text" class="form-control" id="website" name="website"  autocomplete="off" 
              value="<?php echo set_value('website'); ?>"/>
            </div>
          </div> 

          <div class="col-md-4 col-xs-4">
            <div class="form-group">
              <label for="email">Email</label>
              <input type="text" class="form-control" id="email" name="email"  autocomplete="off" 
              value="<?php echo set_value('email'); ?>"/>
            </div>
      </div>         

        </div>

        
    <div class="row">
		
		  <div class="col-md-4 col-xs-4">
            <div class="form-group">
              <label for="contact">Contact Name</label>
              <input type="text" class="form-control" id="contact" name="contact"  autocomplete="off" 
              value="<?php echo set_value('contact'); ?>"/>
            </div>
          </div>
		
			<div class="col-md-4 col-xs-4">
            <div class="form-group">
              <label for="phone">Phone</label>
              <input type="text" class="form-control" id="phone" name="phone"  autocomplete="off" 
              value="<?php echo set_value('phone'); ?>"/>
            </div>
      </div>
		  
		  <div class="col-md-4 col-xs-4">
            <div class="form-group">
              <label for="mobile">Mobile</label>
              <input type="text" class="form-control" id="mobile" name="mobile"  autocomplete="off" 
              value="<?php echo set_value('mobile'); ?>"/>
            </div>
      </div>

      
		  
		</div>
		  
		  
		  <div class="form-group">
              <label for="remark">Remark</label>
              <textarea type="text" class="form-control" rows="4" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark'); ?></textarea>
           </div>

  
       <div class="box-footer">
              <button type="submit" class="btn btn-primary">Save</button>
              <a href="<?php echo base_url('supplier/') ?>" class="btn btn-warning">Back</a>
            </div>
          </form>
        </div>
      </div>
    </div>    

  </section>
</div>



<!-----------------------------------------------   Javascript  ---------------------------------------------------------------->


<script type="text/javascript">

    $(".select_group").select2({width: '100%'});

  
</script>