<div class="content-wrapper">

  <section class="content-header">
    <h1>Update Supplier <?php echo $supplier_data['supplier_name'];?></h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('supplier') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Supplier</li>
    </ol>
  </section>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                       Tab section                                               -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

  <section class="content">

      <ul class="nav nav-tabs">
      <li class="<?php echo (($active_tab === 'supplier') ? 'active' : '')?>"><a data-toggle="tab" href="#supplier">Supplier</a></li>

      <?php if(in_array('viewSupplier', $user_permission)): ?>
        <li class="<?php echo (($active_tab === 'item') ? 'active' : '')?>"><a data-toggle="tab" href="#item">Items</a></li>
      <?php endif; ?> 

      <?php if(in_array('viewSupplier', $user_permission)): ?>
        <li class="<?php echo (($active_tab === 'delivery') ? 'active' : '')?>"><a data-toggle="tab" href="#delivery">Deliveries</a></li>
      <?php endif; ?> 

      <li class="<?php echo (($active_tab === 'document') ? 'active' : '')?>"><a data-toggle="tab" href="#document">Documents</a></li>

    </ul>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        Session variables                                        -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


    <!-- Creation of a session field to keep the supplier id -->
    <?php $this->session->unset_userdata('supplier_id');?>         
    <?php if(empty($this->session->userdata('supplier_id'))) {
      $supplier_id = array('supplier_id' => $supplier_data['supplier_id']);
      $this->session->set_userdata($supplier_id);} ?>  

      
    <!-- Creation of a session to keep the directory for the manipulation
              of upload of documents -->

    <?php $this->session->unset_userdata('directory');?>             
    <?php if(empty($this->session->userdata('directory'))) {
            $directory = array('directory' => '/upload/suppliers/'.$supplier_data['supplier_id'].'/');
            $this->session->set_userdata($directory);
      } ?>   





<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 



    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                  S U P P L I E R                                                -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        



<div id="supplier" class="tab-pane fade <?php echo (($active_tab === 'supplier') ? 'in active' : '') ?>">
<div class="box">
    <form role="form" action="<?php base_url('supplier/update') ?>" method="post" enctype="multipart/form-data">
    <div class="box-body">

      <?php echo validation_errors(); ?>  

       <div class="row">

        <div class="col-md-6 col-xs-6">    
          <div class="form-group">
            <label for="supplier_name">Name <font color="red">*</font></label>
            <input type="text" class="form-control" id="supplier_name" name="supplier_name" autocomplete="off"
            value="<?php echo set_value('supplier_name', isset($supplier_data['supplier_name']) ? $supplier_data['supplier_name'] : ''); ?>" />
          </div>
       </div>
	   
	   <div class="col-md-4 col-xs-4">
          <div class="form-group">
            <label for="tin">TIN</label>
            <input type="text" class="form-control" id="tin" name="tin" autocomplete="off"
            value="<?php echo set_value('tin', isset($supplier_data['tin']) ? $supplier_data['tin'] : ''); ?>" />
          </div>
        </div> 
		
		<div class="col-md-2 col-xs-2" align="center">
          <div class="radio">
            <label><input type="radio" name="active" id="active" class="" <?php if($supplier_data['active']=='1') echo "checked='checked'"; ?> value="1" <?php echo $this->form_validation->set_radio('active', 1); ?> />Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
            <label><input type="radio" name="active" id="active" class="" <?php if($supplier_data['active']=='2') echo "checked='checked'"; ?> value="2" <?php echo $this->form_validation->set_radio('active', 2); ?> />Inactive</label> 
          </div>
        </div>
		
	  </div>	
	   
	   
     <div class="row">
	 
	   <div class="col-md-5 col-xs-5">
          <div class="form-group">
            <label for="address">Address</font></label>
            <input type="text" class="form-control" id="address" name="address" autocomplete="off"
            value="<?php echo set_value('address', isset($supplier_data['address']) ? $supplier_data['address'] : ''); ?>" />
          </div>
        </div>  
		
		    <div class="col-md-3 col-xs-3">
          <div class="form-group">
            <label for="website">Website</label>
            <input type="text" class="form-control" id="website" name="website" autocomplete="off"
            value="<?php echo set_value('website', isset($supplier_data['website']) ? $supplier_data['website'] : ''); ?>" />
          </div>
        </div>

        <div class="col-md-3 col-xs-3">
          <div class="form-group">
            <label for="email">Email</font></label>
            <input type="text" class="form-control" id="email" name="email" autocomplete="off"
            value="<?php echo set_value('email', isset($supplier_data['email']) ? $supplier_data['email'] : ''); ?>" />
          </div>
        </div>

        <div class="col-md-1 col-xs-1">
          <div class="form-group">
            <label for="send mail">Send Mail</label><br>
            <a href="mailto:<?php echo $supplier_data['email']; ?>" class="btn btn-warning">Send</a>
          </div>
        </div>       
		
	 </div>
		
   <div class="row">
	  
	    <div class="col-md-4 col-xs-4">
          <div class="form-group">
            <label for="contact">Contact Name</label>
            <input type="text" class="form-control" id="contact" name="contact" autocomplete="off"
            value="<?php echo set_value('contact', isset($supplier_data['contact']) ? $supplier_data['contact'] : ''); ?>" />
          </div>
        </div> 

        <div class="col-md-4 col-xs-4">
          <div class="form-group">
            <label for="phone">Phone</font></label>
            <input type="text" class="form-control" id="phone" name="phone" autocomplete="off"
            value="<?php echo set_value('phone', isset($supplier_data['phone']) ? $supplier_data['phone'] : ''); ?>" />
          </div>
        </div>  
		
		<div class="col-md-4 col-xs-4">
          <div class="form-group">
            <label for="mobile">Mobile</font></label>
            <input type="text" class="form-control" id="mobile" name="mobile" autocomplete="off"
            value="<?php echo set_value('mobile', isset($supplier_data['mobile']) ? $supplier_data['mobile'] : ''); ?>" />
          </div>
        </div> 

	   </div>		

        

     <div class="form-group">
        <label for="remark">Remark</label>
        <textarea type="text" class="form-control" rows="4" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark', isset($supplier_data['remark']) ? $supplier_data['remark'] : ''); ?></textarea>
     </div>
 
      
    </div>    <!-- /.box-body -->

    <div class="box-footer">
      <button type="submit" class="btn btn-primary">Save</button>
      <?php echo '<a href="'.base_url('report_supplier/report_supplier/'.$supplier_data['supplier_id']).'" target="_blank" class="btn btn-success"><i class="fa fa-print" ></i></a>'; ?>
      <a href="<?php echo base_url('supplier/') ?>" class="btn btn-warning">Back</a>
   </div>

        </form>
    </div>
  </div>


<!------------------------------------------------------------->
<!-- Javascript part of Supplier                          --->
<!------------------------------------------------------------->

<script type="text/javascript">  

    $(".select_group").select2({width: '100%'});

</script>



<!------------------------------------------------------------->
<!-- Load part of codes for item, deliveries and document   --->
<!------------------------------------------------------------->

 <?php if(in_array('viewItem', $user_permission)): ?>
      <?php $this->load->view('supplier/item'); ?> 
 <?php endif; ?> 


 <?php if(in_array('viewSupplier', $user_permission)): ?>
      <?php $this->load->view('supplier/delivery'); ?> 
 <?php endif; ?> 

<?php $this->load->view('supplier/document'); ?>


<!--  End of the form  -->
          </div>
       </div>
   </div>
</section>
</div>
