<div class="content-wrapper">
  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('requisition') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Requisition</li>
    </ol>
    <br>
  </section>


  <section class="content">
   <div class="row">
    <div class="col-md-12 col-xs-12"> 


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        

    <div id="messages"></div>

    <?php if($this->session->flashdata('success')): ?>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?php echo $this->session->flashdata('success'); ?>
      </div>
    <?php elseif($this->session->flashdata('error')): ?>
      <div class="alert alert-error alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?php echo $this->session->flashdata('error'); ?>
      </div>
    <?php endif; ?>


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                    E D I T                                                      -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


<form role="form" action="<?php base_url('requisition/update') ?>" method="post">

  <div class="box">
   
        <div class="box-body">

          <?php echo validation_errors(); ?>

          <div class="row">

          <div class="col-md-10 col-xs-10">
           <h4 class="box-title">Update Requisition </h4>
          </div>

            <div class="col-md-2 col-xs-2">
              <div class="form-group" style="display: flex">
                <label for="requisition_no">Requisition No <?php echo $requisition_data['requisition']['requisition_no']; ?></label> 
                <input type="hidden" class="form-control" id="requisition_no" name="requisition_no" autocomplete="off" 
                value="<?php echo $requisition_data['requisition']['requisition_no']; ?>" disabled  />
              </div>
            </div>  
        </div>

        <div class="row">           

           <div class="col-md-3 col-xs-3">
              <div class="form-group">
                <label for="employee_requested">Requested by</label>               
                <select class="form-control select_group" id="employee_requested" name="employee_requested">
                  <option value=""></option> 
                  <?php foreach ($employee_requested as $k => $v): ?>
                    <option value="<?php echo $v['employee_id'] ?>" <?php if($requisition_data['requisition']['employee_requested_fk'] == $v['employee_id']) { echo "selected='selected'"; } ?> ><?php echo $v['employee_name'] ?></option>
                  <?php endforeach ?>
               </select>             
            </div>
          </div>

          <div class="col-md-1 col-xs-1">
            <div class="form-group">
              <label for="search-plus">More info</label>
               <?php echo '<a href="' . base_url('employee/update/' . $requisition_data['requisition']['employee_requested_fk']) . '" class="btn btn-default"><i class="fa fa-search-plus" style="font-size:20px"></i></a>'; ?>
            </div>
          </div> 

           <div class="col-md-3 col-xs-3">
              <div class="form-group">
                <label for="employee">Approved by</label>
                <select class="form-control select_group" id="employee_approved" name="employee_approved">
                  <option value=""></option> 
                  <?php foreach ($employee_approved as $k => $v): ?>
                    <option value="<?php echo $v['employee_id'] ?>" <?php if($requisition_data['requisition']['employee_approved_fk'] == $v['employee_id']) { echo "selected='selected'"; } ?> ><?php echo $v['employee_name'] ?></option>
                  <?php endforeach ?>
               </select>
              </div>
            </div>

          <div class="col-md-1 col-xs-1">
            
          </div>   

          <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="requisition_date">Requisition Date <font color="red"> *</font></label>
              <input type="date" class="form-control" id="requisition_date" name="requisition_date" autocomplete="off" 
              value="<?php echo set_value('requisition_date', isset($requisition_data['requisition']['requisition_date']) ? $requisition_data['requisition']['requisition_date'] : ''); ?>" align="right"/>
            </div>
          </div>
        </div>
          
          
          <table class="table table-brequisitioned" id="item_info_table">
            <thead>
              <tr>
                <th style="width:50%">Item <font color="red"> *</font></th>
                <th style="width:10%">Qty</th>
                <th style="width:10%">Qty Inventory</th>
                <th style="width:10%"><button type="button" id="add_row" class="btn btn-default"><i class="fa fa-plus"></i></button></th>
              </tr>
            </thead>

             <tbody>

              <?php if(isset($requisition_data['movement'])): ?>
                <?php $x = 1; ?>
                <?php foreach ($requisition_data['movement'] as $key => $val): ?>
                  <?php //print_r($v); ?>
                 <tr id="row_<?php echo $x; ?>">
                   <td>
                    <select class="form-control select_group item" data-row-id="row_<?php echo $x; ?>" id="item_<?php echo $x; ?>" name="item[]" style="width:100%;" onchange="getItemData(<?php echo $x; ?>)" required>
                        <option value=""></option>
                        <?php foreach ($item as $k => $v): ?>
                          <option value="<?php echo $v['item_location_id'] ?>" <?php if($val['item_location_fk'] == $v['item_location_id']) { echo "selected='selected'"; } ?>>(<?php echo $v['item_code'] ?>) <?php echo $v['item_name'] ?> - <?php echo $v['location_name'] ?></option>
                        <?php endforeach ?>
                      </select>
                    </td>
                   <td><input type="text" name="qty[]" id="qty_<?php echo $x; ?>" class="form-control" required value="<?php echo $val['quantity'] ?>" autocomplete="off"></td>  
                    <td><input type="text" name="qty_item[]" id="qty_item_<?php echo $x; ?>" class="form-control" required value="<?php echo $val['quantity_item'] ?>" autocomplete="off" readonly></td>                
              
              <td><button type="button" class="btn btn-default" onclick="removeRow('<?php echo $x; ?>')"><i class="fa fa-close"></i></button></td>
           </tr>
           <?php $x++; ?>
         <?php endforeach; ?>
       <?php endif; ?>
       </tbody>
    </table>
 
  </div>



  <div class="box-footer">

    <div class="row">
      <div class="col-md-6 col-xs-6">
        <button type="submit" class="btn btn-primary">Save</button>
        <?php echo '<a href="'.base_url('report_requisition/report_requisition/'.$requisition_data['requisition']['requisition_id']).'" target="_blank" class="btn btn-success"><i class="fa fa-print" ></i></a>'; ?>
        <a href="<?php echo base_url('requisition/create') ?>" class="btn btn-success">Create New Requisition</a>
        <a href="<?php echo base_url('requisition/') ?>" class="btn btn-warning">Back</a>
      </div>

      <div class="col-md-6 col-xs-6" align="right" >
        Updated by <?php echo $requisition_data['requisition']['updated_by'] ?> on <?php echo $requisition_data['requisition']['updated_date'] ?> 
      </div>
    </div>

  </div>



</form>
</div>
</div>
</div>


</section>
</div>



<!------------------------------------------------------------->
<!-- Javascript part of Requisition                         --->
<!------------------------------------------------------------->

<script type="text/javascript">
  var base_url = "<?php echo base_url(); ?>";

   $(document).ready(function() {
    $(".select_group").select2();

    
    // Add new row in the table 
    $("#add_row").unbind('click').bind('click', function() {
      var table = $("#item_info_table");
      var count_table_tbody_tr = $("#item_info_table tbody tr").length;
      var row_id = count_table_tbody_tr + 1;

      $.ajax({
          url: base_url + '/requisition/getItemLocationData/',
          type: 'post',
          dataType: 'json',
          success:function(response) {
            

              // console.log(reponse.x);
               var html = '<tr id="row_'+row_id+'">'+
                   '<td>'+ 
                    '<select class="form-control select_group item" data-row-id="'+row_id+'" id="item_'+row_id+'" name="item[]" style="width:100%;" onchange="getItemData('+row_id+')">'+
                        '<option value=""></option>';
                        $.each(response, function(index, value) {
                          html += '<option value="'+value.item_location_id+'">('+value.item_code+') '+value.item_name+' - '+value.location_name+'</option>';                   
                        });
                        
                      html += '</select>'+
                    '</td>'+ 
                    '<td><input type="text" name="qty[]" id="qty_'+row_id+'" class="form-control" ></td>'+
                    '<td><input type="text" name="qty_item[]" id="qty_item_'+row_id+'" class="form-control" readonly ></td>'+
                    '<td><button type="button" class="btn btn-default" onclick="removeRow(\''+row_id+'\')"><i class="fa fa-close"></i></button></td>'+
                    '</tr>';

                if(count_table_tbody_tr >= 1) {
                $("#item_info_table tbody tr:last").after(html);  
              }
              else {
                $("#item_info_table tbody").html(html);
              }

              $(".item").select2();

          }
        });

      return false;
    });

  }); // /document

   

  function getItemData(row_id)
  {
    var item_location_id = $("#item_"+row_id).val(); 

    if(item_location_id == "") {
      $("#qty_"+row_id).val("");  
      $("#qty_item_"+row_id).val("");    

    } else {
      $.ajax({
        url: base_url + 'requisition/getItemData',
        type: 'post',
        data: {item_location_id : item_location_id},
        dataType: 'json',
        success:function(response) {
          // Verify if the quantity is possible       
          $("#qty_item_"+row_id).val(response.quantity_item);
          $("#qty_"+row_id).val(1);         
        } // /success
      }); // /ajax function to fetch the item data 
    }
  }



  function removeRow(tr_id)
  {
    $("#item_info_table tbody tr#row_"+tr_id).remove();
    subAmount();
  }
</script>