<div class="content-wrapper">
  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('customer') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Customer</li>
    </ol>
    <br>
  </section>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


  <section class="content">
    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                   A D D    C U S T O M E R                                      -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->


  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Add Customer</h3>
    </div>
    <form role="form" action="<?php base_url('customer/create') ?>" method="post" enctype="multipart/form-data">
        <div class="box-body">

          <?php echo validation_errors(); ?>

         <div class="row">                  
            
            <div class="col-md-5 col-xs-5">
              <div class="form-group">
                <label for="customer_name">Customer name <font color="red">*</font></label>
                <input type="text" class="form-control" id="customer_name" name="customer_name"  autocomplete="off" 
                value="<?php echo set_value('customer_name'); ?>"/>
              </div>
            </div>

            <div class="col-md-2 col-xs-2">
              <div class="form-group">
                <label for="customer_code">Code</label>
                <input type="text" class="form-control" id="customer_code" name="customer_code"  autocomplete="off" 
                value="<?php echo $generate_code['customer_code'] ?>" readonly/>
              </div>
            </div>

            <div class="col-md-2 col-xs-2">
              <div class="form-group">
                <label for="tin">TIN</label>
                <input type="text" class="form-control" id="tin" name="tin"  autocomplete="off" 
                value="<?php echo set_value('tin'); ?>"/>
              </div>
            </div>

            <div class="col-md-3 col-xs-3" align="center">
              <div class="radio">
                  <label><input type="radio" name="active" id="active" value="1" checked="checked" >Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                  <label><input type="radio" name="active" id="active" value="2" >Inactive</label>
              </div>
            </div> 
          </div>    

          <div class="row">

            <div class="col-md-3 col-xs-3">
              <div class="form-group">
                <label for="customer_type">Customer Type <font color="red">*</font></label>
                <select class="form-control select_group" id="customer_type" name="customer_type">
                  <option value=""></option> 
                  <?php foreach ($customer_type as $k => $v): ?>
                  <option value="<?php echo $v['customer_type_id'] ?>" <?php echo set_select('customer_type', $v['customer_type_id']); ?>><?php echo $v['customer_type_name'] ?></option>
                  <?php endforeach ?>
                </select>
              </div>
            </div> 

           <div class="col-md-3 col-xs-3">
              <div class="form-group">
                <label for="area">Area <font color="red">*</font></label>
                <select class="form-control select_group" id="area" name="area">
                  <option value=""></option> 
                  <?php foreach ($area as $k => $v): ?>
                  <option value="<?php echo $v['area_id'] ?>" <?php echo set_select('area', $v['area_id']); ?>><?php echo $v['area_name'] ?></option>
                  <?php endforeach ?>
                </select>
              </div>
            </div> 

            <div class="col-md-3 col-xs-3">
              <div class="form-group">
                <label for="municipality">Municipality</label>
                <select class="form-control select_group" id="municipality" name="municipality">
                  <option value=""></option> 
                  <?php foreach ($municipality as $k => $v): ?>
                  <option value="<?php echo $v['municipality_id'] ?>" <?php echo set_select('municipality', $v['municipality_id']); ?>><?php echo $v['municipality_name'] ?></option>
                  <?php endforeach ?>
                </select>
              </div>
            </div>

            <div class="col-md-3 col-xs-3">
              <div class="form-group">
                <label for="address">Address</label>
                <input type="text" class="form-control" id="address" name="address"  autocomplete="off" 
                value="<?php echo set_value('address'); ?>"/>
              </div>
            </div>

          </div>

          <div class="row">

            <div class="col-md-3 col-xs-3">
              <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" class="form-control" id="phone" name="phone"  autocomplete="off" 
                value="<?php echo set_value('phone'); ?>"/>
              </div>
            </div>

            <div class="col-md-6 col-xs-6">
              <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" id="email" name="email"  autocomplete="off" 
                value="<?php echo set_value('email'); ?>"/>
              </div>
            </div>                 
      
            <div class="col-md-3 col-xs-3">
              <div class="form-group">
                <label for="balance">Balance</label>
                <input type="text" class="form-control" id="balance" name="balance"  autocomplete="off" 
                value="<?php echo set_value('balance'); ?>"/>
              </div>
            </div>
            
        </div>

        <div class="row">

          <div class="col-md-12 col-xs-12">
               <div class="form-group">
                <label for="remark">Remark</label>
                <textarea type="text" class="form-control" rows="3" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark'); ?></textarea>
              </div>
            </div> 

        </div>

        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Save</button>
          <a href="<?php echo base_url('customer/') ?>" class="btn btn-warning">Back</a>
        </div>
      </form>
        </div>
      </div>
    </div>    

  </section>
</div>




<!-----------------------------------------------   Javascript  ---------------------------------------------------------------->


<script type="text/javascript">

    $(".select_group").select2({width: '100%'});

  
</script>