<div class="content-wrapper">
  <section class="content-header">
    <h1>Update Customer <?php echo $customer_data['customer_name'];?></h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('customer') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Customer</li>
    </ol>
  </section>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                       Tab section                                               -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

  <section class="content">

      <ul class="nav nav-tabs">
      <li class="<?php echo (($active_tab === 'customer') ? 'active' : '')?>"><a data-toggle="tab" href="#customer">Customer</a></li>
      <li class="<?php echo (($active_tab === 'order') ? 'active' : '')?>"><a data-toggle="tab" href="#order">Orders</a></li>
      <li class="<?php echo (($active_tab === 'payment') ? 'active' : '')?>"><a data-toggle="tab" href="#payment">Payments</a></li>
      <li class="<?php echo (($active_tab === 'document') ? 'active' : '')?>"><a data-toggle="tab" href="#document">Documents</a></li>

    </ul>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        Session variables                                        -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


    <!-- Creation of a session field to keep the customer id -->
    <?php $this->session->unset_userdata('customer_id');?>         
    <?php if(empty($this->session->userdata('customer_id'))) {
      $customer_id = array('customer_id' => $customer_data['customer_id']);
      $this->session->set_userdata($customer_id);} ?>  


    <!-- Creation of a session to keep the directory for the manipulation
              of upload of documents -->

    <?php $this->session->unset_userdata('directory');?>             
    <?php if(empty($this->session->userdata('directory'))) {
            $directory = array('directory' => '/upload/customers/'.$customer_data['customer_id'].'/');
            $this->session->set_userdata($directory);
      } ?> 




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 



    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        C U S T O M E R                                          -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        



<div id="customer" class="tab-pane fade <?php echo (($active_tab === 'customer') ? 'in active' : '') ?>">
      <div class="box">
         <div class="box-header"></div>
          <form role="form" action="<?php base_url('customer/update') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>  

                 <div class="row">

                  <div class="col-md-5 col-xs-5">    
                    <div class="form-group">
                      <label for="customer_name">Customer name <font color="red">*</font></label>
                      <input type="text" class="form-control" id="customer_name" name="customer_name" autocomplete="off"
                      value="<?php echo set_value('customer_name', isset($customer_data['customer_name']) ? $customer_data['customer_name'] : ''); ?>" />
                    </div>
                 </div> 

                 <div class="col-md-2 col-xs-2">    
                    <div class="form-group">
                      <label for="customer_code">Code</label>
                      <input type="text" class="form-control" id="customer_code" name="customer_code" autocomplete="off"
                      value="<?php echo set_value('customer_code', isset($customer_data['customer_code']) ? $customer_data['customer_code'] : ''); ?>" readonly/>
                    </div>
                 </div> 


                 <div class="col-md-2 col-xs-2">    
                    <div class="form-group">
                      <label for="tin">TIN</label>
                      <input type="text" class="form-control" id="tin" name="tin" autocomplete="off"
                      value="<?php echo set_value('tin', isset($customer_data['tin']) ? $customer_data['tin'] : ''); ?>" />
                    </div>
                 </div> 

                 
                <div class="col-md-3 col-xs-3" align="center">
                    <div class="radio">
                      <label><input type="radio" name="active" id="active" class="" <?php if($customer_data['active']=='1') echo "checked='checked'"; ?> value="1" <?php echo $this->form_validation->set_radio('active', 1); ?> />Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                      <label><input type="radio" name="active" id="active" class="" <?php if($customer_data['active']=='2') echo "checked='checked'"; ?> value="2" <?php echo $this->form_validation->set_radio('active', 2); ?> />Inactive</label> 
                    </div>
                  </div>
                </div>   


                <div class="row">

                   <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="customer_type">Customer Type <font color="red">*</font></label>
                      <select class="form-control select_group" id="customer_type" name="customer_type">
                        <option value=""></option> 
                        <?php foreach ($customer_type as $k => $v): ?>
                          <option value="<?php echo $v['customer_type_id'] ?>" <?php if($customer_data['customer_type_fk'] == $v['customer_type_id']) { echo "selected='selected'"; } ?> ><?php echo $v['customer_type_name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div> 

                                  
                <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="area">Area <font color="red">*</font></label>
                      <select class="form-control select_group" id="area" name="area">
                        <option value=""></option> 
                        <?php foreach ($area as $k => $v): ?>
                          <option value="<?php echo $v['area_id'] ?>" <?php if($customer_data['area_fk'] == $v['area_id']) { echo "selected='selected'"; } ?> ><?php echo $v['area_name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div> 

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="municipality">Municipality</label>
                      <select class="form-control select_group" id="municipality" name="municipality">
                        <option value=""></option> 
                        <?php foreach ($municipality as $k => $v): ?>
                          <option value="<?php echo $v['municipality_id'] ?>" <?php if($customer_data['municipality_fk'] == $v['municipality_id']) { echo "selected='selected'"; } ?> ><?php echo $v['municipality_name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div> 

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="address">Address</font></label>
                      <input type="text" class="form-control" id="address" name="address" autocomplete="off"
                      value="<?php echo set_value('address', isset($customer_data['address']) ? $customer_data['address'] : ''); ?>" />
                    </div>
                  </div>  

                </div>
                
                                
                <div class="row">

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="phone">Phone</font></label>
                      <input type="text" class="form-control" id="phone" name="phone" autocomplete="off"
                      value="<?php echo set_value('phone', isset($customer_data['phone']) ? $customer_data['phone'] : ''); ?>" />
                    </div>
                  </div>  

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="email">Email</font></label>
                      <input type="text" class="form-control" id="email" name="email" autocomplete="off"
                      value="<?php echo set_value('email', isset($customer_data['email']) ? $customer_data['email'] : ''); ?>" />
                    </div>
                  </div> 

                  <div class="col-md-1 col-xs-1">
                    <div class="form-group">
                      <label for="send mail">Send Mail</label><br>
                      <a href="mailto:<?php echo $customer_data['email']; ?>" class="btn btn-warning">Send</a>
                    </div>
                  </div>

                  <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="balance">Balance</font></label>

                      <?php if(in_array('updateBalanceCustomer', $user_permission)): ?>
                        <input type="text" class="form-control" id="balance" name="balance" autocomplete="off" enabled
                        value="<?php echo set_value('balance', isset($customer_data['balance']) ? $customer_data['balance'] : ''); ?>" />
                      <?php else: ?>
                         <input type="text" class="form-control" id="balance" name="balance" autocomplete="off" readonly
                        value="<?php echo set_value('balance', isset($customer_data['balance']) ? $customer_data['balance'] : ''); ?>" />  
                      <?php endif; ?>

                    </div>
                  </div>  
                </div>  



                <div class="row">

                  <div class="col-md-12 col-xs-12">
                     <div class="form-group">
                      <label for="remark">Remark</label>
                      <textarea type="text" class="form-control" rows="3" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark', isset($customer_data['remark']) ? $customer_data['remark'] : ''); ?></textarea>
                    </div>
                  </div>  

                </div>
                
              </div>    <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save</button>
                <?php echo '<a href="'.base_url('report_customer/report_customer/'.$customer_data['customer_id']).'" target="_blank" class="btn btn-success"><i class="fa fa-print" ></i></a>'; ?>
                <a href="<?php echo base_url('customer/') ?>" class="btn btn-warning">Back</a>
              </div>

            </form>
        </div>
      </div>






<!------------------------------------------------------------->
<!-- Javascript part of Customer                            --->
<!------------------------------------------------------------->

<script type="text/javascript">  

    $(".select_group").select2({width: '100%'});

</script>



<!------------------------------------------------------------->
<!-- Load part of codes for order, payment and document     --->
<!------------------------------------------------------------->

<?php $this->load->view('customer/order'); ?>

<?php $this->load->view('customer/payment'); ?>

<?php $this->load->view('customer/document'); ?>



<!--  End of the form  -->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</div>

