<div class="content-wrapper">
  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('employee') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Add Employee</li>
    </ol>
    <br>
  </section>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


  <section class="content">
    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                   A D D    R E S O U R C E                                      -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->


  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Add Employee</h3>
    </div>
    <form role="form" action="<?php base_url('employee/create') ?>" method="post" enctype="multipart/form-data">
        <div class="box-body">

          <?php echo validation_errors(); ?>

       <div class="row">                  

          <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="last_name">Last Name <font color="red">*</font></label>
              <input type="text" class="form-control" id="last_name" name="last_name"  autocomplete="off" 
              value="<?php echo set_value('last_name'); ?>"/>
            </div>
          </div>

          <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="first_name">First Name <font color="red">*</font></label>
              <input type="text" class="form-control" id="first_name" name="first_name"  autocomplete="off" 
              value="<?php echo set_value('first_name'); ?>"/>
            </div>
          </div>

          <div class="col-md-2 col-xs-2">
            <div class="form-group">
              <label for="employee_code">Code</label>
              <input type="text" class="form-control" id="employee_code" name="employee_code"  autocomplete="off" 
              value="<?php echo $generate_code['employee_code']; ?>" readonly />
            </div>
          </div>

          <div class="col-md-2 col-xs-2" align="left">
            <div class="form-group">
              <label for="gender">Gender <font color="red">*</font></label>
                <div class="radio">
                    <label><input type="radio" name="gender" id="gender" value="M" checked="checked" >Male&nbsp;&nbsp;&nbsp;&nbsp;</label>
                    <label><input type="radio" name="gender" id="gender" value="F" >Female&nbsp;&nbsp;&nbsp;&nbsp;</label>
                    <label><input type="radio" name="gender" id="gender" value="O" >Other</label>
                </div>
              </div> 
            </div>

          <div class="col-md-2 col-xs-2" align="center">
            <div class="form-group">
            <div class="radio">
                <label><input type="radio" name="active" id="active" value="1" checked="checked" >Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <label><input type="radio" name="active" id="active" value="2" >Inactive</label>
            </div>
          </div> 
        </div>
        </div>    


        <div class="row">

         <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="employee_type">Type</label>
              <select class="form-control select_group" id="employee_type" name="employee_type">
                <option value=""></option> 
                <?php foreach ($employee_type as $k => $v): ?>
                <option value="<?php echo $v['employee_type_id'] ?>" <?php echo set_select('employee_type', $v['employee_type_id']); ?>><?php echo $v['employee_type_name'] ?></option>
                <?php endforeach ?>
              </select>
            </div>
          </div> 

          <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="employee_status">Civil Status</label>
              <select class="form-control select_group" id="employee_status" name="employee_status">
                <option value=""></option> 
                <?php foreach ($employee_status as $k => $v): ?>
                <option value="<?php echo $v['employee_status_id'] ?>" <?php echo set_select('employee_status', $v['employee_status_id']); ?>><?php echo $v['employee_status_name'] ?></option>
                <?php endforeach ?>
              </select>
            </div>
          </div>

          <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="position">Position</label>
              <select class="form-control select_group" id="position" name="position">
                <option value=""></option> 
                <?php foreach ($position as $k => $v): ?>
                <option value="<?php echo $v['position_id'] ?>" <?php echo set_select('position', $v['position_id']); ?>><?php echo $v['position_name'] ?></option>
                <?php endforeach ?>
              </select>
            </div>
          </div>

          <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label>Department</label>
              <select class="form-control select_group" name="department">
                <option value=""></option> 
                <?php foreach ($department as $k => $v): ?>
                <option value="<?php echo $v['department_id'] ?>" <?php echo set_select('department', $v['department_id']); ?>><?php echo $v['department_name'] ?></option>
                <?php endforeach ?>
              </select>
            </div>
          </div>
        </div>

        <div class="row">

        <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="birthday">Birthday</label>
              <input type="date" class="form-control" id="birthday" name="birthday"  autocomplete="off" 
              value="<?php echo set_value('birthday'); ?>"/>
            </div>
          </div>

            <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="sss">SSS</label>
              <input type="text" class="form-control" id="sss" name="sss"  autocomplete="off" 
              value="<?php echo set_value('sss'); ?>"/>
            </div>
          </div>

           <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="tin">TIN</label>
              <input type="text" class="form-control" id="tin" name="tin"  autocomplete="off" 
              value="<?php echo set_value('tin'); ?>"/>
            </div>
          </div>

           <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="phil_health">Phil Health</label>
              <input type="text" class="form-control" id="phil_health" name="phil_health"  autocomplete="off" 
              value="<?php echo set_value('phil_health'); ?>"/>
            </div>
          </div>

         

         </div>


        <div class="row">        
          
        <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="pag_ibig">PAG-IBIG</label>
              <input type="text" class="form-control" id="pag_ibig" name="pag_ibig"  autocomplete="off" 
              value="<?php echo set_value('pag_ibig'); ?>"/>
            </div>
          </div>

         <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="area">Area</label>
              <select class="form-control select_group" id="area" name="area">
                <option value=""></option> 
                <?php foreach ($area as $k => $v): ?>
                <option value="<?php echo $v['area_id'] ?>" <?php echo set_select('area', $v['area_id']); ?>><?php echo $v['area_name'] ?></option>
                <?php endforeach ?>
              </select>
            </div>
          </div> 

          <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="municipality">Municipality</label>
              <select class="form-control select_group" id="municipality" name="municipality">
                <option value=""></option> 
                <?php foreach ($municipality as $k => $v): ?>
                <option value="<?php echo $v['municipality_id'] ?>" <?php echo set_select('municipality', $v['municipality_id']); ?>><?php echo $v['municipality_name'] ?></option>
                <?php endforeach ?>
              </select>
            </div>
          </div>

          <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="address">Address</label>
              <input type="text" class="form-control" id="address" name="address"  autocomplete="off" 
              value="<?php echo set_value('address'); ?>"/>
            </div>
          </div>

           <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="employment_date">Employment Date</label>
              <input type="date" class="form-control" id="employment_date" name="employment_date"  autocomplete="off" 
              value="<?php echo set_value('employment_date'); ?>"/>
            </div>
          </div>

          <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="phone">Phone</label>
              <input type="text" class="form-control" id="phone" name="phone"  autocomplete="off" 
              value="<?php echo set_value('phone'); ?>"/>
            </div>
          </div>


          <div class="col-md-3 col-xs-3">
            <div class="form-group">
              <label for="email">Email</label>
              <input type="text" class="form-control" id="email" name="email"  autocomplete="off" 
              value="<?php echo set_value('email'); ?>"/>
            </div>
          </div>  

          <div class="col-md-3 col-xs-3">
            <div class="form-group">
            <label for="remark">Remark</label>
            <textarea type="text" class="form-control" rows="3" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark'); ?></textarea>
          </div>
        </div> 

        </div>

       <div class="box-footer">
              <button type="submit" class="btn btn-primary">Save</button>
              <a href="<?php echo base_url('employee/') ?>" class="btn btn-warning">Back</a>
            </div>
          </form>
        </div>
      </div>
    </div>    

  </section>
</div>



<!-----------------------------------------------   Javascript  ---------------------------------------------------------------->


<script type="text/javascript">

    $(".select_group").select2({width: '100%'});

  
</script>