
<div class="content-wrapper">
  <section class="content-header">
    <h1>Employees</h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('dashboard') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Employees</li>
    </ol>
  </section>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

  <section class="content">

    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!-- <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        V I E W    R E S O U R C E                               -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        

        <?php if(in_array('createEmployee', $user_permission)): ?>
            <a href="<?php echo base_url('employee/create') ?>" class="btn btn-primary">Add Employee</a>          
        <?php endif; ?>

        <br /> <br />

        <div class="box">
          <div class="box-header"></div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="manageTable" class="table table-bordered table-striped">
              <thead>
              <tr>                
                <th>Name</th>
                <th>Code</th>
                <th>Type</th>
                <th>Area</th>
                <th>Municipality</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Active</th>
                <?php if(in_array('updateEmployee', $user_permission) || in_array('deleteEmployee', $user_permission)): ?>
                  <th width="18%">Action</th>
                <?php endif; ?>
              </tr>
              </thead>

            </table>
          </div>


<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                   D E L E T E   R E S O U R C E                                 -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

<?php if(in_array('deleteCustomer', $user_permission)): ?>

  <div class="modal fade" tabindex="-1" role="dialog" id="removeModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete Employee</h4>
      </div>

      <form role="form" action="<?php echo base_url('employee/remove') ?>" method="post" id="removeForm">
        <div class="modal-body">
          <p>Delete impossible if orders or documents are linked to this employee.</p>
          <p><font color="red">Delete or modify manually the information related and you will be able to delete.</font></p>
          <p>Do you really want to delete?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Delete</button>
        </div>
      </form>


    </div>
  </div>
</div>


<?php endif; ?>


        </div>
      </div>
    </div>  

  </section>
</div>



<!------------------------------------------------------------->
<!-- Javascript part of Employee                            --->
<!------------------------------------------------------------->


<script type="text/javascript">
var manageTable;
var base_url = "<?php echo base_url(); ?>";

  $("#mainEmployeeNav").addClass('active');

  // initialize the datatable 
  manageTable = $('#manageTable').DataTable({
    'ajax': base_url + 'employee/fetchEmployeeData',    
    'lengthMenu': [[25, 100, -1], [25, 100, "All"]],
      dom:  "<'row'<'col-sm-3'l><'col-sm-6'B><'col-sm-3'f>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-5'i><'col-sm-7'p>>",
      buttons: [
                {extend: 'excel',exportOptions: {columns: ':visible',rows: ':visible'}},
                {extend: 'pdf',pageSize: 'LEGAL',orientation: 'landscape',exportOptions: {columns: ':visible',}},
                {extend: 'print',exportOptions: {columns: ':visible',rows: ':visible'}},                
                'colvis' 
                ]
  });


// remove functions 
function removeFunc(employee_id)
{
  if(employee_id) {
    $("#removeForm").on('submit', function() {

      var form = $(this);

      // remove the text-danger
      $(".text-danger").remove();

      $.ajax({
        url: form.attr('action'),
        type: form.attr('method'),
        data: { employee_id }, 
        dataType: 'json',
        success:function(response) {

          manageTable.ajax.reload(null, false); 

          if(response.success === true) {
            $("#messages").html('<div class="alert alert-success alert-dismissible" role="alert">'+
              '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
              '<strong> <span class="glyphicon glyphicon-ok-sign"></span> </strong>'+response.messages+
            '</div>');           

          } else {

            $("#messages").html('<div class="alert alert-warning alert-dismissible" role="alert">'+
              '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
              '<strong> <span class="glyphicon glyphicon-exclamation-sign"></span> </strong>'+response.messages+
            '</div>'); 
          }

           // hide the modal
            $("#removeModal").modal('hide');
        }
      }); 

      return false;
    });
  }
}


</script>