<div class="content-wrapper">
  <section class="content-header">
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('item') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Item</li>
    </ol>
    <br>
  </section>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


  <section class="content">
    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                   A D D    I T E M                                              -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        


        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Add Item</h3>
          </div>
          <form role="form" action="<?php base_url('item/create') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>

                 <div class="row">                  
                  
                  <div class="col-md-6 col-xs-6">
                    <div class="form-group">
                      <label for="item_name">Item name <font color="red">*</font></label>
                      <input type="text" class="form-control" id="item_name" name="item_name"  autocomplete="off" 
                      value="<?php echo set_value('item_name'); ?>"/>
                    </div>
                  </div>

                  <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="item_code">Code</label>
                      <input type="text" class="form-control" id="item_code" name="item_code"  autocomplete="off" 
                      value="<?php echo set_value('item_code'); ?>"/>
                    </div>
                  </div>

                  <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="item_code">Inventory</label>
                      <div class="radio">
                        <label><input type="radio" name="inventory" id="inventory" value="1" checked="checked">Yes&nbsp;&nbsp;&nbsp;&nbsp;</label>
                        <label><input type="radio" name="inventory" id="inventory" value="2" >No</label>
                    </div>
                    </div>
                  </div>                  

                  <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="item_code">Activity</label>
                        <div class="radio">
                          <label><input type="radio" name="active" id="active" value="1" checked="checked" >Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                          <label><input type="radio" name="active" id="active" value="2" >Inactive</label>
                      </div>
                    </div>
                  </div> 
                </div>    

                <div class="row">

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="category">Category <font color="red">*</font></label>
                      <select class="form-control select_group" id="category" name="category">
                        <option value=""></option> 
                        <?php foreach ($category as $k => $v): ?>
                        <option value="<?php echo $v['category_id'] ?>" <?php echo set_select('category', $v['category_id']); ?>><?php echo $v['category_name'] ?></option>
                        <?php endforeach ?>
                      </select>
                    </div>
                  </div> 

                   <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="unit">Unit</label>
                      <select class="form-control select_group" id="unit" name="unit">
                        <option value=""></option> 
                        <?php foreach ($unit as $k => $v): ?>
                        <option value="<?php echo $v['unit_id'] ?>" <?php echo set_select('unit', $v['unit_id']); ?>><?php echo $v['unit_name'] ?></option>
                        <?php endforeach ?>
                      </select>
                    </div>
                  </div> 

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="brand">Brand</label>
                      <input type="text" class="form-control" id="brand" name="brand"  autocomplete="off"/>
                    </div>
                  </div> 

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="supplier">Main Supplier</label>
                      <select class="form-control select_group" id="supplier" name="supplier">
                        <option value=""></option> 
                        <?php foreach ($supplier as $k => $v): ?>
                        <option value="<?php echo $v['supplier_id'] ?>" <?php echo set_select('supplier', $v['supplier_id']); ?>><?php echo $v['supplier_name'] ?></option>
                        <?php endforeach ?>
                      </select>
                    </div>
                  </div>   

                </div>

                <div class="row">

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="ordering_point">Ordering Point</label>
                      <input type="text" class="form-control" id="ordering_point" name="ordering_point"  autocomplete="off" 
                      value="<?php echo set_value('ordering_point'); ?>"/>
                    </div>
                  </div>

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="safety_stock">Safety Stock</label>
                      <input type="text" class="form-control" id="safety_stock" name="safety_stock"  autocomplete="off" 
                      value="<?php echo set_value('safety_stock'); ?>"/>
                    </div>
                  </div>

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="price_date">Price Date</label>
                      <input type="date" class="form-control" id="price_date" name="price_date" value='<?php echo date('Y-m-d');?>' autocomplete="off">
                    </div>
                  </div>

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="item_price">Price <font color="red">*</font></label>
                      <input type="text" class="form-control" id="item_price" name="item_price" autocomplete="off" 
                      value="<?php echo set_value('item_price'); ?>"/>
                    </div>
                  </div> 

                </div>               

                <div class="row">       

                  <div class="col-md-6 col-xs-6">
                    <div class="form-group">
                      <label for="description">Description</label>
                      <textarea type="text" class="form-control" rows="3" id="description" name="description" autocomplete="off"><?php echo set_value('description'); ?></textarea>
                    </div>
                  </div>  
        
                  <div class="col-md-6 col-xs-6">
                     <div class="form-group">
                      <label for="remark">Remark</label>
                      <textarea type="text" class="form-control" rows="3" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark'); ?></textarea>
                    </div>
                  </div>  
                </div>  

              </div>

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="<?php echo base_url('item/') ?>" class="btn btn-warning">Back</a>
              </div>
            </form>
        </div>
      </div>
    </div>
    </div>    

  </section>
</div>




<<!-----------------------------------------------   Javascript  ---------------------------------------------------------------->


<script type="text/javascript">

    $(".select_group").select2({width: '100%'});

  
</script>