<div class="content-wrapper">

  <section class="content-header">
    <h1>Update Item <?php echo $item_data['item_code'];?></h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('item') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Item</li>
    </ol>
  </section>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                       Tab section                                               -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

  <section class="content">

      <ul class="nav nav-tabs">
      <li class="<?php echo (($active_tab === 'item') ? 'active' : '')?>"><a data-toggle="tab" href="#item">Item</a></li>
      <li class="<?php echo (($active_tab === 'location') ? 'active' : '')?>"><a data-toggle="tab" href="#location">Locations</a></li>
      <?php if(in_array('viewProduction', $user_permission)): ?>
        <li class="<?php echo (($active_tab === 'production') ? 'active' : '')?>"><a data-toggle="tab" href="#production">Production</a></li>  
      <?php endif; ?> 
      <li class="<?php echo (($active_tab === 'movement') ? 'active' : '')?>"><a data-toggle="tab" href="#movement">Movements</a></li>  

    </ul>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        Session variables                                        -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 


    <!-- Creation of a session field to keep the item id -->
    <?php $this->session->unset_userdata('item_id');?>         
    <?php if(empty($this->session->userdata('item_id'))) {
      $item_id = array('item_id' => $item_data['item_id']);
      $this->session->set_userdata($item_id);} ?>  

      





<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 



    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!--<div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>

        <div class="tab-content">




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        I T E M                                                  -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        



<div id="item" class="tab-pane fade <?php echo (($active_tab === 'item') ? 'in active' : '') ?>">
      <div class="box">
          <form role="form" action="<?php base_url('item/update') ?>" method="post" enctype="multipart/form-data">
              <div class="box-body">

                <?php echo validation_errors(); ?>  

                 <div class="row">

                  <div class="col-md-6 col-xs-6">    
                    <div class="form-group">
                      <label for="item_name">Item name <font color="red">*</font></label>
                      <input type="text" class="form-control" id="item_name" name="item_name" autocomplete="off"
                      value="<?php echo set_value('item_name', isset($item_data['item_name']) ? $item_data['item_name'] : ''); ?>" />
                    </div>
                 </div> 

                 <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="item_code">Code</font></label>
                      <input type="text" class="form-control" id="item_code" name="item_code" autocomplete="off"
                      value="<?php echo set_value('item_code', isset($item_data['item_code']) ? $item_data['item_code'] : ''); ?>" />
                    </div>
                  </div>  

                <div class="col-md-2 col-xs-2" align="center">
                  <div class="form-group">
                      <label for="inventory">Inventory</font></label>
                        <div class="radio">
                          <label><input type="radio" name="inventory" id="inventory_yes" class="" <?php if($item_data['inventory']=='1') echo "checked='checked'"; ?> value="1" <?php echo $this->form_validation->set_radio('inventory', 1); ?> />Yes&nbsp;&nbsp;&nbsp;&nbsp;</label>
                          <label><input type="radio" name="inventory" id="inventory_no" class="" <?php if($item_data['inventory']=='2') echo "checked='checked'"; ?> value="2" <?php echo $this->form_validation->set_radio('inventory', 2); ?> />No</label> 
                        </div>
                      </div>
                  </div>  

                <div class="col-md-2 col-xs-2" align="center">
                  <div class="form-group">
                      <label for="active">Activity</font></label>
                        <div class="radio">
                          <label><input type="radio" name="active" id="active" class="" <?php if($item_data['active']=='1') echo "checked='checked'"; ?> value="1" <?php echo $this->form_validation->set_radio('active', 1); ?> />Active&nbsp;&nbsp;&nbsp;&nbsp;</label>
                          <label><input type="radio" name="active" id="active" class="" <?php if($item_data['active']=='2') echo "checked='checked'"; ?> value="2" <?php echo $this->form_validation->set_radio('active', 2); ?> />Inactive</label> 
                        </div>
                      </div>
                  </div>

                </div>   


                <div class="row">
                                  
                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="category">Category <font color="red">*</font></label>
                      <select class="form-control select_group" id="category" name="category">
                        <option value=""></option> 
                        <?php foreach ($category as $k => $v): ?>
                          <option value="<?php echo $v['category_id'] ?>" <?php if($item_data['category_fk'] == $v['category_id']) { echo "selected='selected'"; } ?> ><?php echo $v['category_name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div>  

                   <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="unit">Unit</label>
                      <select class="form-control select_group" id="unit" name="unit">
                        <option value=""></option> 
                        <?php foreach ($unit as $k => $v): ?>
                          <option value="<?php echo $v['unit_id'] ?>" <?php if($item_data['unit_fk'] == $v['unit_id']) { echo "selected='selected'"; } ?> ><?php echo $v['unit_name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div>                  

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="brand">Brand</font></label>
                      <input type="text" class="form-control" id="brand" name="brand" autocomplete="off"
                      value="<?php echo set_value('brand', isset($item_data['brand']) ? $item_data['brand'] : ''); ?>" />
                    </div>
                  </div>  

                  <div class="col-md-3 col-xs-3">
                    <div class="form-group">
                      <label for="supplier">Main Supplier</label>
                      <select class="form-control select_group" id="supplier" name="supplier">
                        <option value=""></option> 
                        <?php foreach ($supplier as $k => $v): ?>
                          <option value="<?php echo $v['supplier_id'] ?>" <?php if($item_data['supplier_fk'] == $v['supplier_id']) { echo "selected='selected'"; } ?> ><?php echo $v['supplier_name'] ?></option>
                        <?php endforeach ?>
                     </select>
                    </div>
                  </div> 

                </div>
                
                                
                <div class="row">

                  <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="ordering_point">Ordering Point</font></label>
                      <input type="text" class="form-control" id="ordering_point" name="ordering_point" autocomplete="off"
                      value="<?php echo set_value('ordering_point', isset($item_data['ordering_point']) ? $item_data['ordering_point'] : ''); ?>" />
                    </div>
                  </div>  

                  <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="safety_stock">Safety Stock</font></label>
                      <input type="text" class="form-control" id="safety_stock" name="safety_stock" autocomplete="off"
                      value="<?php echo set_value('safety_stock', isset($item_data['safety_stock']) ? $item_data['safety_stock'] : ''); ?>" />
                    </div>
                  </div>  


                  <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="price_date">Price Date</label>
                      <input type="date" class="form-control" id="price_date" name="price_date" autocomplete="off" 
                      value="<?php echo set_value('price_date', isset($item_data['price_date']) ? $item_data['price_date'] : ''); ?>" />
                    </div>
                  </div>        
                  
                  <div class="col-md-2 col-xs-2">
                    <div class="form-group">
                      <label for="item_price">Price <font color="red">*</font></label>
                      <input type="text" class="form-control" id="item_price" name="item_price" autocomplete="off" 
                      value="<?php echo set_value('item_price', isset($item_data['item_price']) ? $item_data['item_price'] : ''); ?>" />
                    </div>
                  </div> 

                  <div class="col-md-2 col-xs-2">
                    <div class="form-group"> 
                         <label for="quantity_inv">
                          <input type="label_quantity_inv" style="padding: 2px 1px; border: 0px" id="label_quantity_inv" name="label_quantity_inv"/>
                      </label> 
                         <input type="text" class="form-control" id="quantity_inv" name="quantity_inv" autocomplete="off" disabled
                         value="<?php echo $item_data['quantity'] ?>" />
                     </div>
                  </div> 

                   <div class="col-md-2 col-xs-2">
                    <div class="form-group"> 
                      <label for="total_value">
                        <input type="label_total_value" style="padding: 2px 1px; border: 0px" id="label_total_value" name="label_total_value"/>
                      </label>
                         <input type="text" class="form-control" id="total_value" name="total_value" autocomplete="off" disabled
                         value="<?php echo number_format(($item_data['quantity'] * $item_data['item_price']),2) ?>" />
                     </div>
                  </div> 
                </div>    
              
                <div class="row">       

                  <div class="col-md-6 col-xs-6">
                    <div class="form-group">
                      <label for="description">Description</label>
                      <textarea type="text" class="form-control" rows="3" id="description" name="description" autocomplete="off"><?php echo set_value('description', isset($item_data['description']) ? $item_data['description'] : ''); ?></textarea>
                    </div>
                  </div>  
        
                  <div class="col-md-6 col-xs-6">
                     <div class="form-group">
                      <label for="remark">Remark</label>
                      <textarea type="text" class="form-control" rows="3" id="remark" name="remark" autocomplete="off"><?php echo set_value('remark', isset($item_data['remark']) ? $item_data['remark'] : ''); ?></textarea>
                    </div>
                  </div>  
                </div>  
                
              </div>    <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save</button>
                <?php echo '<a href="'.base_url('report_item/report_item/'.$item_data['item_id']).'" target="_blank" class="btn btn-success"><i class="fa fa-print" ></i></a>'; ?>
                <a href="<?php echo base_url('item/') ?>" class="btn btn-warning">Back</a>
              </div>

            </form>
        </div>
      </div>






<!------------------------------------------------------------->
<!-- Javascript part of Item                                --->
<!------------------------------------------------------------->

<script type="text/javascript">  

    $(".select_group").select2({width: '100%'});

    //--> If there is no inventory for this item, we hide the quantity and total value

    var label_quantity_inv = 'Quantity Inventory';
    var label_total_value = 'Total Value';

    if(document.getElementById('inventory_yes').checked) {
       document.getElementById("quantity_inv").style.visibility = "visible";
       document.getElementById("total_value").style.visibility = "visible";
       label_quantity_inv = 'Quantity Inventory';
       $("#label_quantity_inv").val(label_quantity_inv);  
       label_total_value = 'Total Value';
       $("#label_total_value").val(label_total_value);   
    }else if(document.getElementById('inventory_no').checked) {
       document.getElementById("quantity_inv").style.visibility = "hidden";
       document.getElementById("total_value").style.visibility = "hidden";
       label_quantity_inv = '';
       $("#label_quantity_inv").val(label_quantity_inv);
       label_total_value = '';
       $("#label_total_value").val(label_total_value);
    }   

        

</script>



<!-------------------------------------------------------------->
<!-- Load part of codes for location, production and movement -->
<!-------------------------------------------------------------->

<?php $this->load->view('item/location'); ?>

 <?php if(in_array('viewProduction', $user_permission)): ?>
      <?php $this->load->view('item/production'); ?>  
 <?php endif; ?> 

<?php $this->load->view('item/movement'); ?>
