
<div class="content-wrapper">
  <section class="content-header">
    <h1>Items</h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo base_url('dashboard') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Items</li>
    </ol>
  </section>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                             Error messages generated by the submit                              -->  
<!--                                                                                                 -->  
<!-----------------------------------------------------------------------------------------------------> 

  <section class="content">

    <div class="row">
      <div class="col-md-12 col-xs-12">

        <div id="messages"></div>

        <?php if($this->session->flashdata('success')): ?>
          <!-- <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('success'); ?>
          </div>--> 
        <?php elseif($this->session->flashdata('error')): ?>
          <div class="alert alert-error alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $this->session->flashdata('error'); ?>
          </div>
        <?php endif; ?>



<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        V I E W    I T E M                                       -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->        

        <?php if(in_array('createItem', $user_permission)): ?>
            <a href="<?php echo base_url('item/create') ?>" class="btn btn-primary">Add Item</a>          
        <?php endif; ?>

        <?php if(in_array('viewItem', $user_permission)): ?>
                 <a href="<?php echo base_url('report11/REP11') ?>" class="btn btn-primary" target="_blank">Inventory Control</a>    
        <?php endif; ?> 

        <br /> <br />

        <div class="box">
          <div class="box-header">
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="manageTable" class="table table-bordered table-striped">
              <thead>
              <tr>                
                <th>Item Name</th>
                <th>Code</th>
                <th>Category</th>
                <th>Unit</th>
                <th>Price</th>
                <th>Total Quantity</th>
                <th>Ordering Point</th>
                <th>Status</th>
                <?php if(in_array('updateItem', $user_permission) || in_array('deleteItem', $user_permission)): ?>
                  <th width="24%">Action</th>
                <?php endif; ?>
              </tr>
              </thead>

            </table>
          </div>
        </div>
      </div>
    </div>
    

  </section>
</div>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                   D E L E T E    I T E M                                        -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->

<?php if(in_array('deleteItem', $user_permission)): ?>

  <div class="modal fade" tabindex="-1" role="dialog" id="removeModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete Item</h4>
      </div>

      <form role="form" action="<?php echo base_url('item/remove') ?>" method="post" id="removeForm">
        <div class="modal-body">
          <p>Delete impossible if orders are linked to this item.</p>
          <p><font color="red">Delete or modify manually the information related and you will be able to delete.</font></p>
          <p>Do you really want to delete?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Delete</button>
        </div>
      </form>

    </div>
  </div>
</div>

<?php endif; ?>




<!-----------------------------------------------------------------------------------------------------> 
<!--                                                                                                 --> 
<!--                                        M O V E M E N T                                          -->  
<!--                                                                                                 -->  
<!----------------------------------------------------------------------------------------------------->

<?php if(in_array('updateItem', $user_permission)): ?>
<div class="modal fade" tabindex="-1" role="dialog" id="movementModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Movement</h4>            
          
      </div>

      <form role="form" action="<?php echo base_url('item/movement') ?>" method="post" id="createForm">

        <div class="modal-body">         

          <div class="row">
            <div class="col-md-9 col-xs-9">
              <div class="form-group">              
                <label for="Item">Item</label>
                <input type="text" class="form-control" id="item_name_movement" name="item_name_movement" disabled autocomplete="off">
                <input type="hidden" id="item_id_movement" name="item_id_movement">
              </div>
            </div>
            <div class="col-md-3 col-xs-3">
              <div class="radio" align="right">
                <label><input type='radio' name='item_type_movement' id='item_type_movement_in' value='1' >In&nbsp;&nbsp;&nbsp;</label>
                <label><input type='radio' name='item_type_movement' id='item_type_movement_out' value='2' checked='checked' >Out</label></td></tr>
              </div>
            </div>
          </div>  

          <div class="form-group">
            <label>Location<font color="red"> *</font></label>
              <select name="item_location_movement" id="item_location_movement" class="form-control" style="width: 100%;">
              </select>
          </div>          

          <div class="row">
            <div class="col-md-6 col-xs-6">
              <div class="form-group">
                <label for="item_quantity_movement">Quantity</label>
                <input type="number" class="form-control" id="item_quantity_movement" name="item_quantity_movement"autocomplete="off">
              </div>
            </div> 
            <div class="col-md-6 col-xs-6">
              <div class="form-group">
                <label for="item_date_movement">Date<font color="red"> *</font></label>
                <input type="date" class="form-control" id="item_date_movement" name="item_date_movement" value='<?php echo date('Y-m-d');?>' autocomplete="off">
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="item_remark_movement">Remark</label>
            <input type="text" class="form-control" id="item_remark_movement" name="item_remark_movement" autocomplete="off">
          </div>
          
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>

      </form>


    </div>
  </div>
</div>
<?php endif; ?>



<!------------------------------------------------------------->
<!-- Javascript part of Movement                            --->
<!------------------------------------------------------------->


<script type="text/javascript">
var manageTable;
var base_url = "<?php echo base_url(); ?>";

  $("#mainItemNav").addClass('active');

  // initialize the datatable 
  manageTable = $('#manageTable').DataTable({
    'ajax': base_url + 'item/fetchItemData',    
    'lengthMenu': [[100, -1], [100, "All"]],
    'order': [[7, 'desc']],
      dom:  "<'row'<'col-sm-3'l><'col-sm-6'B><'col-sm-3'f>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-5'i><'col-sm-7'p>>",
      buttons: [
                {extend: 'excel',exportOptions: {columns: ':visible',rows: ':visible'}},
                {extend: 'pdf',pageSize: 'LEGAL',orientation: 'landscape',exportOptions: {columns: ':visible',}},
                {extend: 'print',exportOptions: {columns: ':visible',rows: ':visible'}},
                'colvis' 
                ]
  });



// Movement inventory
function movement(item_id,item_type_movement)
{
//---> creation of the drop-down list item location
    $item_location_movement = $('[id="item_location_movement"]');    
    $.ajax({
        url: base_url+'item/fetchItemLocation/'+item_id,
        dataType: "JSON", 
        success: function (data) {
            $item_location_movement.html('<option value=""></option>');
            //iterate over the data and append a select option
            $.each(data, function (key, val) {
                $item_location_movement.append('<option value="' + val.item_location_id + '">' + val.location_name + ' (Qty = ' + val.quantity + ')' + '</option>');
            }); 
            
        }, 
        error: function () {
        //if there is an error append a 'none available' option
        $item_location_movement.html('<option id="-1">none available</option>');
        }
    });


    $.ajax({
    url:  base_url+ 'item/fetchItemDataById/'+item_id,
    type: 'post',
    dataType: 'json',
    success:function(response) {
    
      $("#item_name_movement").val(response.item_name);
      $("#item_id_movement").val(response.item_id);}

    }); 

    if(item_type_movement==1){
          $('input:radio[id=item_type_movement_in]')[0].checked = true;     
          $('input:radio[id=item_type_movement_out]')[0].checked = false;            
        }else{
          $('input:radio[id=item_type_movement_in]')[0].checked = false;
          $('input:radio[id=item_type_movement_out]')[0].checked = true;
        }   


// submit the create from 
  $("#createForm").unbind('submit').on('submit', function() {
    var form = $(this);     

    // remove the text-danger
    $(".text-danger").remove();

    $.ajax({
      url: form.attr('action'),
      type: form.attr('method'),
      data: form.serialize(), // /converting the form data into array and sending it to server
      dataType: 'json',
      success:function(response) {

        manageTable.ajax.reload(null, false); 

        if(response.success === true) {
         /* $("#messages").html('<div class="alert alert-success alert-dismissible" role="alert">'+
            '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
            '<strong> <span class="glyphicon glyphicon-ok-sign"></span> </strong>'+response.messages+
          '</div>');*/

          // hide the modal
          $("#movementModal").modal('hide');

          // reset the form
          $("#createForm")[0].reset();
          $("#createForm .form-group").removeClass('has-error').removeClass('has-success');

        } else {

          if(response.messages instanceof Object) {
            $.each(response.messages, function(index, value) {
              var id = $("#"+index);

              id.closest('.form-group')
              .removeClass('has-error')
              .removeClass('has-success')
              .addClass(value.length > 0 ? 'has-error' : 'has-success');
              
              id.after(value);

            });
          } else {
            $("#messages").html('<div class="alert alert-warning alert-dismissible" role="alert">'+
              '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
              '<strong> <span class="glyphicon glyphicon-exclamation-sign"></span> </strong>'+response.messages+
            '</div>'); }
        }
      }
    }); 


    return false;
  });
}


// remove functions 
function removeFunc(item_id)
{
  if(item_id) {
    $("#removeForm").on('submit', function() {

      var form = $(this);

      // remove the text-danger
      $(".text-danger").remove();

      $.ajax({
        url: form.attr('action'),
        type: form.attr('method'),
        data: { item_id }, 
        dataType: 'json',
        success:function(response) {

          manageTable.ajax.reload(null, false); 

          if(response.success === true) {
            $("#messages").html('<div class="alert alert-success alert-dismissible" role="alert">'+
              '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
              '<strong> <span class="glyphicon glyphicon-ok-sign"></span> </strong>'+response.messages+
            '</div>');           

          } else {

            $("#messages").html('<div class="alert alert-warning alert-dismissible" role="alert">'+
              '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
              '<strong> <span class="glyphicon glyphicon-exclamation-sign"></span> </strong>'+response.messages+
            '</div>'); 
          }

           // hide the modal
            $("#removeModal").modal('hide');
        }
      }); 

      return false;
    });
  }
}


</script>